### ISSUE TITLE
Issue installing dephell with pip install -e . on Windows 10

### ISSUE THREAD

**Issue by rwalton00** [dephell/dephell#110]
I'm having an issue installing the dephell developer version on Windows 10 using `pip install -e .` in a virtual environment based on Python 3.7.1. I'm seeing the following output:

```
PS C:\Users\Rob\Documents\Projects\dephell> py -3 -m venv C:\Users\Rob\Documents\Projects\venvs\dephell-dev
PS C:\Users\Rob\Documents\Projects\dephell> C:\Users\Rob\Documents\Projects\venvs\dephell-dev\Scripts\Activate.ps1
(dephell-dev) PS C:\Users\Rob\Documents\Projects\dephell> pip install -e .
Obtaining file:///C:/Users/Rob/Documents/Projects/dephell
  Installing build dependencies ... done
Collecting aiohttp (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/bc/bd/08f0900d62b4ea1ca10bb2e2a1596ac3b04024c7daf7350debee0bd022fb/aiohttp-3.5.4-cp37-cp37m-win_amd64.whl
Collecting appdirs (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting attrs (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting cerberus (from dephell==0.7.3)
  Downloading https://files.pythonhosted.org/packages/c9/0e/f78e23b778c2234972d364d0f8bea2de0a09f450f65d3f05ce091dd0f104/Cerberus-1.3.1.tar.gz (52kB)
    100% |████████████████████████████████| 61kB 405kB/s
Collecting dephell-archive (from dephell==0.7.3)
  Downloading https://files.pythonhosted.org/packages/e8/f3/b467e57fe488d86cb77b5e2a5abca7788d758f4878672d347fc49054a1a9/dephell_archive-0.1.4-py3-none-any.whl
Collecting dephell-discover (from dephell==0.7.3)
  Downloading https://files.pythonhosted.org/packages/88/77/617d334bbfb6dd40ded8ff0beb19d4bb7e794ebe897111288cb21249c681/dephell_discover-0.2.1-py3-none-any.whl
Collecting dephell-licenses (from dephell==0.7.3)
  Downloading https://files.pythonhosted.org/packages/6c/76/5fc0e09745dceeeb0724e75c7b6a2bbafe155c268eab2c3b623d33373d75/dephell_licenses-0.1.5-py3-none-any.whl
Collecting dephell-links (from dephell==0.7.3)
  Downloading https://files.pythonhosted.org/packages/44/90/d9ee3a6773747141eb189af05e2dd89b43e9baa482944cd56e9b3c8887cb/dephell_links-0.1.3-py3-none-any.whl
Collecting dephell-markers (from dephell==0.7.3)
  Downloading https://files.pythonhosted.org/packages/4f/96/e45bb277704d9331a1eb968ff65a3541795f86817d26a502cf94474d638e/dephell_markers-0.2.5-py3-none-any.whl
Collecting dephell-pythons (from dephell==0.7.3)
  Downloading https://files.pythonhosted.org/packages/cf/8a/6320516ec4542562775efdcdd42bef39974c903ae11119b680911f6ff09e/dephell_pythons-0.1.10-py3-none-any.whl
Collecting dephell-shells (from dephell==0.7.3)
  Downloading https://files.pythonhosted.org/packages/c7/c8/d75e5b13d7cd01e640c90a0e264ab4d12b729fb74cf348a9fe1bd56f15b5/dephell_shells-0.1.2-py3-none-any.whl
Collecting dephell-specifier>=0.1.4 (from dephell==0.7.3)
  Downloading https://files.pythonhosted.org/packages/e8/79/dfdc6d5df3b6dc29b610e150465b5193b5c1a66dab16787d6202135f8af4/dephell_specifier-0.1.6-py3-none-any.whl
Collecting dephell-venvs (from dephell==0.7.3)
  Downloading https://files.pythonhosted.org/packages/b6/9c/ca83f185b30cd2ce4bf15b37e1d26a5876880a439e65dd5b021c259e30a4/dephell_venvs-0.1.15-py3-none-any.whl
Collecting jinja2 (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl
Collecting m2r (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/39/e7/9fae11a45f5e1a3a21d8a98d02948e597c4afd7848a0dbe1a1ebd235f13e/m2r-0.2.1.tar.gz
Collecting packaging (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/91/32/58bc30e646e55eab8b21abf89e353f59c0cc02c417e42929f4a9546e1b1d/packaging-19.0-py2.py3-none-any.whl
Collecting pip>=18.0 (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl
Collecting pyyaml (from dephell==0.7.3)
  Downloading https://files.pythonhosted.org/packages/b6/74/c3e15707516f80192059dde32c9d78f00a88c9f3c4d1efd76cbc8d5b0a20/PyYAML-5.1-cp37-cp37m-win_amd64.whl (215kB)
    100% |████████████████████████████████| 225kB 783kB/s
Collecting requests (from dephell==0.7.3)
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 15.4MB/s
Requirement already satisfied: setuptools in c:\users\rob\documents\projects\venvs\dephell-dev\lib\site-packages (from dephell==0.7.3) (39.0.1)
Collecting tomlkit (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/71/c6/06c014b92cc48270765d6a9418d82239b158d8a9b69e031b0e2c6598740b/tomlkit-0.5.3-py2.py3-none-any.whl
Collecting yaspin (from dephell==0.7.3)
  Downloading https://files.pythonhosted.org/packages/d9/2c/c0b8ab9decf35e5770e0b7b20740b9bc114c5880e2af2c8ec6ca95637717/yaspin-0.14.3-py2.py3-none-any.whl
Collecting multidict<5.0,>=4.0 (from aiohttp->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/38/c7/07d8d88c3c16fe65d8596da429d104229dd7433b07432694a3ab45a72eaa/multidict-4.5.2-cp37-cp37m-win_amd64.whl
Collecting chardet<4.0,>=2.0 (from aiohttp->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting async-timeout<4.0,>=3.0 (from aiohttp->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Collecting yarl<2.0,>=1.0 (from aiohttp->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/7d/dc/fb3617b3de980566b54b1ae59eb72fc72810350d7ed9164b26f155fa682d/yarl-1.3.0-cp37-cp37m-win_amd64.whl
Collecting attr (from dephell-discover->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/de/be/ddc7f84d4e087144472a38a373d3e319f51a6faf6e5fc1ae897173675f21/attr-0.3.1.tar.gz
Collecting shellingham (from dephell-shells->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/2d/ac/e8a34d4b3d24bf554f40651b2aac549a3fc7223725bf10fbdfe2083b6372/shellingham-1.3.1-py2.py3-none-any.whl
Collecting pexpect (from dephell-shells->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/0e/3e/377007e3f36ec42f1b84ec322ee12141a9e10d808312e5738f52f80a232c/pexpect-4.7.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/65/c6/2399700d236d1dd681af8aebff1725558cddfd6e43d7a5184a675f4711f5/MarkupSafe-1.1.1-cp37-cp37m-win_amd64.whl
Collecting mistune (from m2r->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/09/ec/4b43dae793655b7d8a25f76119624350b4d65eb663459eb9603d7f1f0345/mistune-0.8.4-py2.py3-none-any.whl
Collecting docutils (from m2r->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl
Collecting six (from packaging->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/dd/d9/3ec19e966301a6e25769976999bd7bbe552016f0d32b577dc9d63d2e0c49/pyparsing-2.4.0-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->dephell==0.7.3)
  Downloading https://files.pythonhosted.org/packages/39/ec/d93dfc69617a028915df914339ef66936ea976ef24fa62940fd86ba0326e/urllib3-1.25.2-py2.py3-none-any.whl (150kB)
    100% |████████████████████████████████| 153kB 20.5MB/s
Collecting idna<2.9,>=2.5 (from requests->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect->dephell-shells->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
dephell 0.7.3 requires dephell-archive, which is not installed.
dephell 0.7.3 requires dephell-discover, which is not installed.
dephell 0.7.3 requires dephell-licenses, which is not installed.
dephell 0.7.3 requires dephell-links, which is not installed.
dephell 0.7.3 requires dephell-markers, which is not installed.
dephell 0.7.3 requires dephell-pythons, which is not installed.
dephell 0.7.3 requires dephell-shells, which is not installed.
dephell 0.7.3 requires dephell-specifier>=0.1.4, which is not installed.
dephell 0.7.3 requires dephell-venvs, which is not installed.
Installing collected packages: multidict, attrs, chardet, async-timeout, idna, yarl, aiohttp, appdirs, cerberus, dephell-archive, attr, dephell-discover, urllib3, certifi, requests, dephell-licenses, dephell-links, six, pyparsing, packaging, dephell-specifier, dephell-markers, dephell-pythons, shellingham, ptyprocess, pexpect, dephell-shells, dephell-venvs, MarkupSafe, jinja2, mistune, docutils, m2r, pip, pyyaml, tomlkit, yaspin, dephell
  Running setup.py install for cerberus ... done
  Running setup.py install for attr ... done
  Running setup.py install for m2r ... done
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\Rob\\AppData\\Local\\Temp\\pip-uninstall-6gbo85_b\\users\\rob\\documents\\projects\\venvs\\dephell-dev\\scripts\\pip.exe'
Consider using the `--user` option or check the permissions.
```

I can see it runs into an issue after it uninstalls `pip` to do the upgrade to `pip` version 19. So I manually upgraded `pip` in a clean venv before running `pip install -e.` again.

This time I saw a slightly different error message:

```
PS C:\Users\Rob\Documents\Projects\dephell> py -3 -m venv depvenv
PS C:\Users\Rob\Documents\Projects\dephell> .\depvenv\Scripts\Activate.ps1
(depvenv) PS C:\Users\Rob\Documents\Projects\dephell> python -m pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-19.1.1
(depvenv) PS C:\Users\Rob\Documents\Projects\dephell> python -m pip install -e .
Obtaining file:///C:/Users/Rob/Documents/Projects/dephell
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting dephell-venvs (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/b6/9c/ca83f185b30cd2ce4bf15b37e1d26a5876880a439e65dd5b021c259e30a4/dephell_venvs-0.1.15-py3-none-any.whl
Collecting aiohttp (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/bc/bd/08f0900d62b4ea1ca10bb2e2a1596ac3b04024c7daf7350debee0bd022fb/aiohttp-3.5.4-cp37-cp37m-win_amd64.whl
Collecting tomlkit (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/71/c6/06c014b92cc48270765d6a9418d82239b158d8a9b69e031b0e2c6598740b/tomlkit-0.5.3-py2.py3-none-any.whl
Collecting packaging (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/91/32/58bc30e646e55eab8b21abf89e353f59c0cc02c417e42929f4a9546e1b1d/packaging-19.0-py2.py3-none-any.whl
Requirement already satisfied: pip>=18.0 in c:\users\rob\documents\projects\dephell\depvenv\lib\site-packages (from dephell==0.7.3) (19.1.1)
Collecting m2r (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/39/e7/9fae11a45f5e1a3a21d8a98d02948e597c4afd7848a0dbe1a1ebd235f13e/m2r-0.2.1.tar.gz
Collecting appdirs (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting cerberus (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/c9/0e/f78e23b778c2234972d364d0f8bea2de0a09f450f65d3f05ce091dd0f104/Cerberus-1.3.1.tar.gz
Collecting attrs (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting jinja2 (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl
Requirement already satisfied: setuptools in c:\users\rob\documents\projects\dephell\depvenv\lib\site-packages (from dephell==0.7.3) (39.0.1)
Collecting dephell-pythons (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/cf/8a/6320516ec4542562775efdcdd42bef39974c903ae11119b680911f6ff09e/dephell_pythons-0.1.10-py3-none-any.whl
Collecting requests (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting dephell-links (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/44/90/d9ee3a6773747141eb189af05e2dd89b43e9baa482944cd56e9b3c8887cb/dephell_links-0.1.3-py3-none-any.whl
Collecting yaspin (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/d9/2c/c0b8ab9decf35e5770e0b7b20740b9bc114c5880e2af2c8ec6ca95637717/yaspin-0.14.3-py2.py3-none-any.whl
Collecting dephell-archive (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/e8/f3/b467e57fe488d86cb77b5e2a5abca7788d758f4878672d347fc49054a1a9/dephell_archive-0.1.4-py3-none-any.whl
Collecting dephell-discover (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/88/77/617d334bbfb6dd40ded8ff0beb19d4bb7e794ebe897111288cb21249c681/dephell_discover-0.2.1-py3-none-any.whl
Collecting dephell-licenses (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/6c/76/5fc0e09745dceeeb0724e75c7b6a2bbafe155c268eab2c3b623d33373d75/dephell_licenses-0.1.5-py3-none-any.whl
Collecting pyyaml (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/b6/74/c3e15707516f80192059dde32c9d78f00a88c9f3c4d1efd76cbc8d5b0a20/PyYAML-5.1-cp37-cp37m-win_amd64.whl
Collecting dephell-markers (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/4f/96/e45bb277704d9331a1eb968ff65a3541795f86817d26a502cf94474d638e/dephell_markers-0.2.5-py3-none-any.whl
Collecting dephell-shells (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/c7/c8/d75e5b13d7cd01e640c90a0e264ab4d12b729fb74cf348a9fe1bd56f15b5/dephell_shells-0.1.2-py3-none-any.whl
Collecting dephell-specifier>=0.1.4 (from dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/e8/79/dfdc6d5df3b6dc29b610e150465b5193b5c1a66dab16787d6202135f8af4/dephell_specifier-0.1.6-py3-none-any.whl
Collecting multidict<5.0,>=4.0 (from aiohttp->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/38/c7/07d8d88c3c16fe65d8596da429d104229dd7433b07432694a3ab45a72eaa/multidict-4.5.2-cp37-cp37m-win_amd64.whl
Collecting chardet<4.0,>=2.0 (from aiohttp->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting async-timeout<4.0,>=3.0 (from aiohttp->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Collecting yarl<2.0,>=1.0 (from aiohttp->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/7d/dc/fb3617b3de980566b54b1ae59eb72fc72810350d7ed9164b26f155fa682d/yarl-1.3.0-cp37-cp37m-win_amd64.whl
Collecting six (from packaging->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/dd/d9/3ec19e966301a6e25769976999bd7bbe552016f0d32b577dc9d63d2e0c49/pyparsing-2.4.0-py2.py3-none-any.whl
Collecting mistune (from m2r->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/09/ec/4b43dae793655b7d8a25f76119624350b4d65eb663459eb9603d7f1f0345/mistune-0.8.4-py2.py3-none-any.whl
Collecting docutils (from m2r->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/65/c6/2399700d236d1dd681af8aebff1725558cddfd6e43d7a5184a675f4711f5/MarkupSafe-1.1.1-cp37-cp37m-win_amd64.whl
Collecting certifi>=2017.4.17 (from requests->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/39/ec/d93dfc69617a028915df914339ef66936ea976ef24fa62940fd86ba0326e/urllib3-1.25.2-py2.py3-none-any.whl
Collecting attr (from dephell-discover->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/de/be/ddc7f84d4e087144472a38a373d3e319f51a6faf6e5fc1ae897173675f21/attr-0.3.1.tar.gz
Collecting pexpect (from dephell-shells->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/0e/3e/377007e3f36ec42f1b84ec322ee12141a9e10d808312e5738f52f80a232c/pexpect-4.7.0-py2.py3-none-any.whl
Collecting shellingham (from dephell-shells->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/2d/ac/e8a34d4b3d24bf554f40651b2aac549a3fc7223725bf10fbdfe2083b6372/shellingham-1.3.1-py2.py3-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect->dephell-shells->dephell==0.7.3)
  Using cached https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
ERROR: dephell 0.7.3 requires dephell-archive, which is not installed.
ERROR: dephell 0.7.3 requires dephell-discover, which is not installed.
ERROR: dephell 0.7.3 requires dephell-licenses, which is not installed.
ERROR: dephell 0.7.3 requires dephell-links, which is not installed.
ERROR: dephell 0.7.3 requires dephell-markers, which is not installed.
ERROR: dephell 0.7.3 requires dephell-pythons, which is not installed.
ERROR: dephell 0.7.3 requires dephell-shells, which is not installed.
ERROR: dephell 0.7.3 requires dephell-specifier>=0.1.4, which is not installed.
ERROR: dephell 0.7.3 requires dephell-venvs, which is not installed.
Installing collected packages: six, pyparsing, packaging, dephell-specifier, attrs, dephell-pythons, dephell-venvs, multidict, chardet, async-timeout, idna, yarl, aiohttp, tomlkit, mistune, docutils, m2r, appdirs, cerberus, MarkupSafe, jinja2, certifi, urllib3, requests, dephell-links, yaspin, dephell-archive, attr, dephell-discover, dephell-licenses, pyyaml, dephell-markers, ptyprocess, pexpect, shellingham, dephell-shells, dephell
  Running setup.py install for m2r ... done
  Running setup.py install for cerberus ... done
  Running setup.py install for attr ... done
  Running setup.py develop for dephell
Successfully installed MarkupSafe-1.1.1 aiohttp-3.5.4 appdirs-1.4.3 async-timeout-3.0.1 attr-0.3.1 attrs-19.1.0 cerberus-1.3.1 certifi-2019.3.9 chardet-3.0.4 dephell-venvs dephell-archive dephell-discover dephell-licenses dephell-links dephell-markers dephell-pythons dephell-shells dephell-specifier dephell-venvs docutils-0.14 idna-2.8 jinja2-2.10.1 m2r-0.2.1 mistune-0.8.4 multidict-4.5.2 packaging-19.0 pexpect-4.7.0 ptyprocess-0.6.0 pyparsing-2.4.0 pyyaml-5.1 requests-2.22.0 shellingham-1.3.1 six-1.12.0 tomlkit-0.5.3 urllib3-1.25.2 yarl-1.3.0 yaspin-0.14.3
(depvenv) PS C:\Users\Rob\Documents\Projects\dephell> dephell
Traceback (most recent call last):
  File "C:\Users\Rob\Documents\Projects\dephell\depvenv\Scripts\dephell-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:\Users\Rob\Documents\Projects\dephell\depvenv\lib\site-packages\pkg_resources\__init__.py", line 3088, in <module>
    @_call_aside
  File "C:\Users\Rob\Documents\Projects\dephell\depvenv\lib\site-packages\pkg_resources\__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\Rob\Documents\Projects\dephell\depvenv\lib\site-packages\pkg_resources\__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Users\Rob\Documents\Projects\dephell\depvenv\lib\site-packages\pkg_resources\__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "C:\Users\Rob\Documents\Projects\dephell\depvenv\lib\site-packages\pkg_resources\__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\Rob\Documents\Projects\dephell\depvenv\lib\site-packages\pkg_resources\__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dephell-pythons' distribution was not found and is required by dephell
```

**Comment by orsinium** [comment]
Hmmm :thinking:. That's really strange bug in pip. I see that dephell-pythons "was successfully installed" in this output. We have to get rid of pip >.<

Thank you for issue, Rob. Could you, please, provide "pip freeze" output for depenv?

**Comment by orsinium** [comment]
Ugh, I've found it. pip installs it as `dephell-pythons-0.1.10.dist-info`, but `pkg_resources` parses it as `dephell` name and `pythons` version >.<

**Comment by rwalton00** [comment]
Sorry, been a bit busy over the last day or so. I can provide the output of `pip freeze` if it's still needed. Might take me a bit though as I've since removed the venv.

**Comment by rwalton00** [comment]
Here's the output of `pip freeze`:

```
aiohttp==3.5.4
appdirs==1.4.3
async-timeout==3.0.1
attr==0.3.1
attrs==19.1.0
Cerberus==1.3.1
certifi==2019.3.9
chardet==3.0.4
-e git+https://github.com/dephell/dephell.git@eae9b19bb22f1e69fe4c836554851178835fdb7c#egg=dephell
docutils==0.14
idna==2.8
Jinja2==2.10.1
m2r==0.2.1
MarkupSafe==1.1.1
mistune==0.8.4
multidict==4.5.2
packaging==19.0
pexpect==4.7.0
ptyprocess==0.6.0
pyparsing==2.4.0
PyYAML==5.1
requests==2.22.0
shellingham==1.3.1
six==1.12.0
tomlkit==0.5.3
urllib3==1.25.2
yarl==1.3.0
yaspin==0.14.3
```

Thanks for looking into it. Looking forward to getting this up and running!

**Comment by orsinium** [comment]
Please, try again :)
