### ISSUE TITLE
Domain pattern for configuring custom warehouses is unclear

### ISSUE THREAD

**Issue by dbanty** [dephell/dephell#170]
Example shows this
```toml
[tool.dephell.main]
warehouse = ["example1.com", "example2.com"]
```
When in reality, providing just a domain seems to fail.
```toml
[tool.dephell.main]
from = "pyproject.toml"
to = "poetry.lock"
warehouse = "example.com"
```

```bash
$ dephell deps convert --traceback
ERROR TypeError: must be str, not NoneType
Traceback (most recent call last):
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/cli.py", line 77, in main
    result = task()
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/commands/deps_convert.py", line 42, in __call__
    resolver = loader.load_resolver(path=self.config['from']['path'])
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/converters/base.py", line 68, in load_resolver
    root = self.load(path)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/converters/base.py", line 33, in load
    return self.loads(stream.read())
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/converters/poetry.py", line 103, in loads
    envs=envs.get(name),
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/converters/poetry.py", line 253, in _make_deps
    repo=get_repo(),
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/__init__.py", line 35, in get_repo
    return WareHouseRepo()
  File "<attrs generated init 3fc2b4035cc9de6ff007efaa6337228d85f079dc>", line 6, in __init__
    self.url = __attr_converter_url(__attr_factory_url())
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/warehouse.py", line 61, in _process_url
    return parsed.scheme + '://' + hostname + path
TypeError: must be str, not NoneType
```
Seems like scheme is required.  Putting an https:// in front of example.com seems to fix it.  Also not clear if you need to provide something like /simple/ at the end of the url or if dephell figures out that on its own?

**Comment by dbanty** [comment]
[PEBKAC](https://en.wikipedia.org/wiki/User_error#PEBKAC)
