### ISSUE TITLE
deps install timestamp value error

### ISSUE THREAD

**Issue by dbanty** [dephell/dephell#172]
Note that this looks like it's a problem with logging an error.  There is a real failure here which I can see with --traceback, I'll create that separately as another issue.  This is probably related to custom warehouses (noted `Message: b"Cloning into 'simple'...\nfatal: unable to access '/my.custom.domain/simple/': <url> malformed\n"` in the below traceback).

```toml
[tool.dephell.main]
from = "pyproject.toml"
to = "poetry.lock"
```

```bash
$ dephell deps install
INFO get dependencies (format=poetrylock, path=poetry.lock)
INFO build dependencies graph...
⠋ resolving...--- Logging error ---
Traceback (most recent call last):
  File "/Users/dylan/.pyenv/versions/3.6.8/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/Users/dylan/.pyenv/versions/3.6.8/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/logging_helpers.py", line 100, in format
    record.msg = Fore.WHITE + record.msg + Fore.RESET
TypeError: must be str, not bytes
Call stack:
  File "/Users/dylan/.pyenv/versions/3.6.8/bin/dephell", line 10, in <module>
    sys.exit(entrypoint())
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/cli.py", line 95, in entrypoint
    exit(main(argv[1:]))
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/cli.py", line 77, in main
    result = task()
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/commands/deps_install.py", line 50, in __call__
    resolved = resolver.resolve(silent=self.config['silent'])
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 84, in resolve
    resolved = self._resolve(debug=debug, silent=silent, level=level, spinner=spinner)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 111, in _resolve
    no_conflicts = self._apply_deps(deps, debug=debug)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 184, in _apply_deps
    conflict = self.apply(dep)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 47, in apply
    if not other_dep.compat:
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/models/dependency.py", line 146, in compat
    for group in self.groups:
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/models/groups.py", line 168, in __iter__
    release = self.releases[0]
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/utils.py", line 42, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/models/groups.py", line 33, in releases
    releases = self.dep.repo.get_releases(self.dep)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/git/git.py", line 74, in get_releases
    for tag, time in reversed(self.tags.items()):
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/utils.py", line 42, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/git/git.py", line 40, in tags
    self._setup()
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/git/git.py", line 180, in _setup
    path=self.path.parent,
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/git/git.py", line 137, in _call
    logger.error(result.stderr)
Message: b"Cloning into 'simple'...\nfatal: unable to access '/my.custom.domain/simple/': <url> malformed\n"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/Users/dylan/.pyenv/versions/3.6.8/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/Users/dylan/.pyenv/versions/3.6.8/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/logging_helpers.py", line 100, in format
    record.msg = Fore.WHITE + record.msg + Fore.RESET
TypeError: must be str, not bytes
Call stack:
  File "/Users/dylan/.pyenv/versions/3.6.8/bin/dephell", line 10, in <module>
    sys.exit(entrypoint())
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/cli.py", line 95, in entrypoint
    exit(main(argv[1:]))
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/cli.py", line 77, in main
    result = task()
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/commands/deps_install.py", line 50, in __call__
    resolved = resolver.resolve(silent=self.config['silent'])
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 84, in resolve
    resolved = self._resolve(debug=debug, silent=silent, level=level, spinner=spinner)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 111, in _resolve
    no_conflicts = self._apply_deps(deps, debug=debug)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 184, in _apply_deps
    conflict = self.apply(dep)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 47, in apply
    if not other_dep.compat:
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/models/dependency.py", line 146, in compat
    for group in self.groups:
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/models/groups.py", line 168, in __iter__
    release = self.releases[0]
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/utils.py", line 42, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/models/groups.py", line 33, in releases
    releases = self.dep.repo.get_releases(self.dep)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/git/git.py", line 74, in get_releases
    for tag, time in reversed(self.tags.items()):
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/utils.py", line 42, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/git/git.py", line 41, in tags
    tags = self._call('tag')
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/git/git.py", line 137, in _call
    logger.error(result.stderr)
Message: b'fatal: not a git repository (or any of the parent directories): .git\n'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/Users/dylan/.pyenv/versions/3.6.8/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/Users/dylan/.pyenv/versions/3.6.8/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/logging_helpers.py", line 100, in format
    record.msg = Fore.WHITE + record.msg + Fore.RESET
TypeError: must be str, not bytes
Call stack:
  File "/Users/dylan/.pyenv/versions/3.6.8/bin/dephell", line 10, in <module>
    sys.exit(entrypoint())
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/cli.py", line 95, in entrypoint
    exit(main(argv[1:]))
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/cli.py", line 77, in main
    result = task()
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/commands/deps_install.py", line 50, in __call__
    resolved = resolver.resolve(silent=self.config['silent'])
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 84, in resolve
    resolved = self._resolve(debug=debug, silent=silent, level=level, spinner=spinner)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 111, in _resolve
    no_conflicts = self._apply_deps(deps, debug=debug)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 184, in _apply_deps
    conflict = self.apply(dep)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 47, in apply
    if not other_dep.compat:
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/models/dependency.py", line 146, in compat
    for group in self.groups:
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/models/groups.py", line 168, in __iter__
    release = self.releases[0]
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/utils.py", line 42, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/models/groups.py", line 33, in releases
    releases = self.dep.repo.get_releases(self.dep)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/git/git.py", line 74, in get_releases
    for tag, time in reversed(self.tags.items()):
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/utils.py", line 42, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/git/git.py", line 42, in tags
    result = [(tag, self._get_rev_time(tag)) for tag in tags]
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/git/git.py", line 42, in <listcomp>
    result = [(tag, self._get_rev_time(tag)) for tag in tags]
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/git/git.py", line 141, in _get_rev_time
    data = self._call('show', '-s', r'--format="%cI"', rev)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/git/git.py", line 137, in _call
    logger.error(result.stderr)
Message: b'fatal: not a git repository (or any of the parent directories): .git\n'
Arguments: ()
ERROR ValueError: time data '' does not match format '%Y-%m-%dT%H:%M:%S%z'
```

**Comment by dbanty** [comment]
[PEBKAC](https://en.wikipedia.org/wiki/User_error#PEBKAC)
