### ISSUE TITLE
FileNotFoundError: .git directory not found in project cache

### ISSUE THREAD

**Issue by dbanty** [dephell/dephell#173]
May be related to #171 which seems to convert my poetry.lock into using Git somehow?

```toml
[tool.dephell.main]
from = "pyproject.toml"
to = "poetry.lock"
```

```bash
$ dephell deps install --traceback
INFO get dependencies (format=poetrylock, path=poetry.lock)
INFO build dependencies graph...
ERROR FileNotFoundError: .git directory not found in project cache
Traceback (most recent call last):
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/cli.py", line 77, in main
    result = task()
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/commands/deps_install.py", line 50, in __call__
    resolved = resolver.resolve(silent=self.config['silent'])
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 84, in resolve
    resolved = self._resolve(debug=debug, silent=silent, level=level, spinner=spinner)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 111, in _resolve
    no_conflicts = self._apply_deps(deps, debug=debug)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 184, in _apply_deps
    conflict = self.apply(dep)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 47, in apply
    if not other_dep.compat:
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/models/dependency.py", line 146, in compat
    for group in self.groups:
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/models/groups.py", line 168, in __iter__
    release = self.releases[0]
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/utils.py", line 42, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/models/groups.py", line 33, in releases
    releases = self.dep.repo.get_releases(self.dep)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/git/git.py", line 74, in get_releases
    for tag, time in reversed(self.tags.items()):
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/utils.py", line 42, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/git/git.py", line 40, in tags
    self._setup()
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/git/git.py", line 175, in _setup
    raise FileNotFoundError('.git directory not found in project cache')
FileNotFoundError: .git directory not found in project cache
```

**Comment by dbanty** [comment]
[PEBKAC](https://en.wikipedia.org/wiki/User_error#PEBKAC)
