### ISSUE TITLE
FileExistsError when converting from pyproject.toml to poetry.lock

### ISSUE THREAD

**Issue by dbanty** [dephell/dephell#174]
```toml
[tool.dephell.main]
from = "pyproject.toml"
to = "poetry.lock"
```

```bash
$ dephell deps convert --traceback
ERROR FileExistsError: [Errno too many egg-info] [ArchivePath(archive_path=PosixPath('/var/folders/xr/tq65qlbx2dn1qr8c74ft2rph0000gn/T/tmptodwia2g/Pillow-1.0.tar.gz'), cache_path=PosixPath('/var/folders/xr/tq65qlbx2dn1qr8c74ft2rph0000gn/T/tmpn8xl_6ir'), member_path=PurePosixPath('Pillow-1.0/PIL.egg-info')), ArchivePath(archive_path=PosixPath('/var/folders/xr/tq65qlbx2dn1qr8c74ft2rph0000gn/T/tmptodwia2g/Pillow-1.0.tar.gz'), cache_path=PosixPath('/var/folders/xr/tq65qlbx2dn1qr8c74ft2rph0000gn/T/tmpn8xl_6ir'), member_path=PurePosixPath('Pillow-1.0/Pillow.egg-info'))]
Traceback (most recent call last):
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/cli.py", line 77, in main
    result = task()
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/commands/deps_convert.py", line 56, in __call__
    resolved = resolver.resolve(silent=self.config['silent'])
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 84, in resolve
    resolved = self._resolve(debug=debug, silent=silent, level=level, spinner=spinner)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 111, in _resolve
    no_conflicts = self._apply_deps(deps, debug=debug)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 184, in _apply_deps
    conflict = self.apply(dep)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/resolver.py", line 47, in apply
    if not other_dep.compat:
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/models/dependency.py", line 146, in compat
    for group in self.groups:
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/models/groups.py", line 179, in __iter__
    loop.run_until_complete(future)
  File "/Users/dylan/.pyenv/versions/3.6.8/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/models/groups.py", line 137, in _fetch_releases_deps
    await asyncio.gather(*tasks)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/models/groups.py", line 83, in _fetch_missed_deps
    responses = await asyncio.gather(*tasks)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/warehouse.py", line 122, in get_dependencies
    deps = await asyncio.gather(asyncio.ensure_future(task))
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/warehouse.py", line 271, in _get_from_json
    return await self._get_from_files(response['urls'])
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/warehouse.py", line 301, in _get_from_files
    return await self._download_and_parse(url=file_info['url'], converter=converer)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/repositories/warehouse.py", line 333, in _download_and_parse
    root = converter.load(path)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/converters/sdist.py", line 55, in load
    root = converter.load_dir(*paths)
  File "/Users/dylan/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/converters/egginfo.py", line 62, in load_dir
    raise FileExistsError('too many egg-info', paths)
FileExistsError: [Errno too many egg-info] [ArchivePath(archive_path=PosixPath('/var/folders/xr/tq65qlbx2dn1qr8c74ft2rph0000gn/T/tmptodwia2g/Pillow-1.0.tar.gz'), cache_path=PosixPath('/var/folders/xr/tq65qlbx2dn1qr8c74ft2rph0000gn/T/tmpn8xl_6ir'), member_path=PurePosixPath('Pillow-1.0/PIL.egg-info')), ArchivePath(archive_path=PosixPath('/var/folders/xr/tq65qlbx2dn1qr8c74ft2rph0000gn/T/tmptodwia2g/Pillow-1.0.tar.gz'), cache_path=PosixPath('/var/folders/xr/tq65qlbx2dn1qr8c74ft2rph0000gn/T/tmpn8xl_6ir'), member_path=PurePosixPath('Pillow-1.0/Pillow.egg-info'))]
```

**Comment by EarthModule** [comment]
I ran into same issue when trying to add deps
```
dephell deps add isort[myproject]
ERROR FileExistsError: [Errno too many egg-info] [ArchivePath(archive_path=PosixPath('/tmp/tmp1wakahd5/Pillow-1.0.tar.gz'), cache_path=PosixPath('/tmp/tmpdvle90mq'), member_path=PurePosixPath('Pillow-1.0/PIL.egg-info')), ArchivePath(archive_path=PosixPath('/tmp/tmp1wakahd5/Pillow-1.0.tar.gz'), cache_path=PosixPath('/tmp/tmpdvle90mq'), member_path=PurePosixPath('Pillow-1.0/Pillow.egg-info'))] 
```

**Comment by orsinium** [comment]
@EarthModule as a side note, it should be `isort[pyproject]`, not `isort[myproject]`

**Comment by orsinium** [comment]
Reproduced:

```python
dephell deps tree "Pillow==1.0"
```

Reason: Pillow 1.0 has `PIL.egg-info` and `Pillow.egg-info` at the same time.

**Comment by Exagone313** [comment]
I rapidly edited the code to remove the exception and it works (it takes the first egg-info found), it should be possible to edit the code so it takes all egg-info files (also got that issue with Pillow).
