### ISSUE TITLE
Can't resolve version for dependency with extra requirements

### ISSUE THREAD

**Issue by kammala** [dephell/dephell#236]
When I am trying to install requirements with `extra_requires` block from private repo(artifactory in our case), `dephell deps install` fails with `LookupError.

### Steps to reproduce:
*requirements.txt*:
```
dephell[full]
```
*command to run*:
```
> env REQUESTS_CA_BUNDLE=<path/to/cert> dephell deps install --from-path=requirements.txt --traceback --level DEBUG --warehouse https://<your_company_private_warehouse>/api/pypi/pypi/simple
```
*actual output*:
```
WARNING cannot find config file 
INFO get dependencies (format=pip, path=reqs2.txt)
INFO build dependencies graph... 
ERROR LookupError: cannot find releases for dephell[full] 
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.7/site-packages/dephell/cli.py", line 79, in main
    result = task()
  File "/tmp/venv/lib/python3.7/site-packages/dephell/commands/deps_install.py", line 38, in __call__
    resolver = self._get_locked(default_envs={'main'})
  File "/tmp/venv/lib/python3.7/site-packages/dephell/commands/base.py", line 105, in _get_locked
    return self._resolve(resolver=resolver, default_envs=default_envs)
  File "/tmp/venv/lib/python3.7/site-packages/dephell/commands/base.py", line 111, in _resolve
    resolved = resolver.resolve(silent=self.config['silent'])
  File "/tmp/venv/lib/python3.7/site-packages/dephell/controllers/_resolver.py", line 86, in resolve
    resolved = self._resolve(debug=debug, silent=silent, level=level, spinner=spinner)
  File "/tmp/venv/lib/python3.7/site-packages/dephell/controllers/_resolver.py", line 113, in _resolve
    no_conflicts = self._apply_deps(deps, debug=debug)
  File "/tmp/venv/lib/python3.7/site-packages/dephell/controllers/_resolver.py", line 190, in _apply_deps
    conflict = self.apply(dep)
  File "/tmp/venv/lib/python3.7/site-packages/dephell/controllers/_resolver.py", line 49, in apply
    if not other_dep.compat:
  File "/tmp/venv/lib/python3.7/site-packages/dephell/models/dependency.py", line 152, in compat
    for group in self.groups:
  File "/tmp/venv/lib/python3.7/site-packages/dephell/models/groups.py", line 168, in __iter__
    release = self.releases[0]
  File "/tmp/venv/lib/python3.7/site-packages/dephell/cached_property.py", line 17, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/tmp/venv/lib/python3.7/site-packages/dephell/models/groups.py", line 42, in releases
    raise LookupError('cannot find releases for ' + self.dep.name)
LookupError: cannot find releases for dephell[full]
```

**Comment by orsinium** [comment]
There are no releases for dephell in your repo, aren't it?

**Comment by orsinium** [comment]
curl .../simple/dephell

**Comment by kammala** [comment]
no, they are there. the same command works as expected if I put just `dephell` without `[full]` in the `requirements.txt`

**Comment by kammala** [comment]
you can also reproduce this problem locally via running e.g. [nexus3 in docker](https://hub.docker.com/r/sonatype/nexus3/)

while `pip install -r /tmp/reqs2.txt -i http://localhost:8081/repository/mirror/simple  --trusted-host localhost:8081` works, `dephell deps install --from-path=/tmp/reqs2.txt --from-format=pip --warehouse http://localhost:8081/repository/mirror/simple --traceback --level DEBUG` throws an error(not sure if it is related to current issue though):
```
WARNING cannot find config file 
INFO get dependencies (format=pip, path=/tmp/reqs2.txt)
ERROR FileNotFoundError: cannot find directory: http://localhost:8081/repository/mirror/simple 
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.7/site-packages/dephell/cli.py", line 79, in main
    result = task()
  File "/tmp/venv/lib/python3.7/site-packages/dephell/commands/deps_install.py", line 38, in __call__
    resolver = self._get_locked(default_envs={'main'})
  File "/tmp/venv/lib/python3.7/site-packages/dephell/commands/base.py", line 103, in _get_locked
    resolver = loader.load_resolver(path=loader_config['path'])
  File "/tmp/venv/lib/python3.7/site-packages/dephell/converters/base.py", line 68, in load_resolver
    root = self.load(path=path)
  File "/tmp/venv/lib/python3.7/site-packages/dephell/converters/pip.py", line 71, in load
    editable=req.editable,
  File "/tmp/venv/lib/python3.7/site-packages/dephell/controllers/_dependency.py", line 60, in from_requirement
    repo=get_repo(link),
  File "/tmp/venv/lib/python3.7/site-packages/dephell/repositories/_getter.py", line 29, in get_repo
    repo.attach_config()
  File "/tmp/venv/lib/python3.7/site-packages/dephell/controllers/_repos.py", line 98, in attach_config
    self.add_repo(url=url, from_config=True)
  File "/tmp/venv/lib/python3.7/site-packages/dephell/controllers/_repos.py", line 61, in add_repo
    raise FileNotFoundError('cannot find directory: {}'.format(url))
FileNotFoundError: cannot find directory: http://localhost:8081/repository/mirror/simple
```
```
