### ISSUE TITLE
TypeError: unhashable type: 'list' while reading poetry project's poetry.lock

### ISSUE THREAD

**Issue by jayvdb** [dephell/dephell#256]
```sh
git clone https://github.com/sdispater/poetry
cd poetry
pip-run https://github.com/dephell/dephell/archive/master.zip -- -m dephell deps convert --from poetry.lock --to setup.py`
ERROR TypeError: unhashable type: 'list'
```
Currently this is the input file https://github.com/sdispater/poetry/blob/cb8dc0d94e68042f120441b4e30d89c92598b40e/poetry.lock

**Comment by orsinium** [comment]
Thank you, I'll dive in it

```
ERROR TypeError: unhashable type: 'Container' 
Traceback (most recent call last):
  File "/tmp/pip-run-iehbr2cb/dephell/cli.py", line 115, in main
    result = task()
  File "/tmp/pip-run-iehbr2cb/dephell/commands/deps_convert.py", line 46, in __call__
    resolver = loader.load_resolver(path=self.config['from']['path'])
  File "/tmp/pip-run-iehbr2cb/dephell/converters/base.py", line 94, in load_resolver
    root = self.load(path=path)
  File "/tmp/pip-run-iehbr2cb/dephell/converters/base.py", line 54, in load
    root = self.loads(content=stream.read())
  File "/tmp/pip-run-iehbr2cb/dephell/converters/poetrylock.py", line 63, in loads
    repo=root.repo,
  File "/tmp/pip-run-iehbr2cb/dephell/converters/poetrylock.py", line 163, in _make_deps
    subcontent = ','.join(set(subcontent))
TypeError: unhashable type: 'Container'

```

**Comment by orsinium** [comment]
Yeah, and I did catch it too:

```
Traceback (most recent call last):
  File "/tmp/pip-run-n3__h6bo/dephell/cli.py", line 115, in main
    result = task()
  File "/tmp/pip-run-n3__h6bo/dephell/commands/deps_convert.py", line 46, in __call__
    resolver = loader.load_resolver(path=self.config['from']['path'])
  File "/tmp/pip-run-n3__h6bo/dephell/converters/base.py", line 94, in load_resolver
    root = self.load(path=path)
  File "/tmp/pip-run-n3__h6bo/dephell/converters/base.py", line 54, in load
    root = self.loads(content=stream.read())
  File "/tmp/pip-run-n3__h6bo/dephell/converters/poetrylock.py", line 63, in loads
    repo=root.repo,
  File "/tmp/pip-run-n3__h6bo/dephell/converters/poetrylock.py", line 149, in _make_deps
    envs=envs,
  File "/tmp/pip-run-n3__h6bo/dephell/controllers/_dependency.py", line 110, in from_params
    marker = Markers(marker)
  File "/tmp/pip-run-n3__h6bo/dephell_markers/_markers.py", line 23, in __init__
    self._marker = self._convert(markers)
  File "/tmp/pip-run-n3__h6bo/dephell_markers/_markers.py", line 169, in _convert
    return OrMarker(*cls._deduplicate(new_groups))
  File "/tmp/pip-run-n3__h6bo/dephell_markers/_markers.py", line 199, in _deduplicate
    if merged_node == node:
  File "/tmp/pip-run-n3__h6bo/dephell_markers/_operation/_base.py", line 88, in __eq__
    return self.op == other.op and set(self.nodes) == set(other.nodes)
  File "/tmp/pip-run-n3__h6bo/dephell_markers/_operation/_base.py", line 91, in __hash__
    return hash(self.nodes)
TypeError: unhashable type: 'list'
> /tmp/pip-run-n3__h6bo/dephell_markers/_operation/_base.py(91)__hash__()
-> return hash(self.nodes)
(Pdb) !self.nodes
[StringMarker(lhs=<Variable('sys_platform')>, op=<Op('==')>, rhs=<Value('linux2')>), StringMarker(lhs=<Variable('sys_platform')>, op=<Op('==')>, rhs=<Value('linux')>)]
```

**Comment by DavHau** [comment]
Still an issue.
```bash
git clone https://github.com/python-poetry/poetry
cd poetry
dephell deps tree --from-format poetrylock --from-path poetry.lock
ERROR TypeError: unhashable type: 'Container'
```
