### ISSUE TITLE
On any command: The 'dephell' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by MrMrRobat** [dephell/dephell#266]
When I run any command with dephell, I get this error:
```py
$ dephell
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/dephell", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/rocky/Library/Python/3.6/lib/python/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/Users/rocky/Library/Python/3.6/lib/python/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/Users/rocky/Library/Python/3.6/lib/python/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/rocky/Library/Python/3.6/lib/python/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Users/rocky/Library/Python/3.6/lib/python/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/rocky/Library/Python/3.6/lib/python/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dephell' distribution was not found and is required by the application
```

Tried to reinstall dephell, did not solve the issue.

Not sure, if it's related to dephell itself, or caused by something in my system, but decided to open issue anyway, so If I'd find solution, I could share it here.

**Comment by orsinium** [comment]
Hmmm :thinking:  Could you provide `pip show dephell` and `cat $(which dephell)` outputs?

**Comment by MrMrRobat** [comment]
Well, it seems, that now it works just fine. I didn't do anything specific, just rebooted system once.

Anyway, attaching outputs of commands (added `$ which dephell` as well):
```bash
~
$ pip show dephell  # outputs nothing

~
$ which dephell
/Library/Frameworks/Python.framework/Versions/3.8/bin/dephell
~
$ cat $(which dephell)
#!/Users/rocky/.local/share/dephell/venvs/dephell/bin/python3
# -*- coding: utf-8 -*-
import re
import sys

from dephell.cli import entrypoint

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(entrypoint())
```

I guess something just is or was messed up in my system.

But until problem is solved, closing this issue, thank you!

**Comment by orsinium** [comment]
You had 3.6 before, and now it's 3.8
