### ISSUE TITLE
Unable to use dephell on Windows

### ISSUE THREAD

**Issue by austinv11** [dephell/dephell#272]
Dephell installs perfectly fine, however it appears the docker command breaks any attempt at usage of dephell on windows.

The full traceback is below but its because dockerpty requires the stdlib module `fnctl` which is not available on windows.

```
Traceback (most recent call last):
  File "C:\Users\austi\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\austi\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\austi\PycharmProjects\wrap-it\venv\Scripts\dephell.exe\__main__.py", line 5, in <module>
  File "c:\users\austi\pycharmprojects\wrap-it\venv\lib\site-packages\dephell\cli.py", line 9, in <module>
    from .commands import COMMANDS
  File "c:\users\austi\pycharmprojects\wrap-it\venv\lib\site-packages\dephell\commands\__init__.py", line 2, in <module>
    from .discover import COMMANDS
  File "c:\users\austi\pycharmprojects\wrap-it\venv\lib\site-packages\dephell\commands\discover.py", line 73, in <module>
    module = import_module('.' + module_name, package=package)
  File "C:\Users\austi\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\austi\pycharmprojects\wrap-it\venv\lib\site-packages\dephell\commands\auth.py", line 10, in <module>
    from .base import BaseCommand
  File "c:\users\austi\pycharmprojects\wrap-it\venv\lib\site-packages\dephell\commands\base.py", line 13, in <module>
    from ..actions import attach_deps, get_python_env
  File "c:\users\austi\pycharmprojects\wrap-it\venv\lib\site-packages\dephell\actions\__init__.py", line 6, in <module>
    from ._converting import attach_deps
  File "c:\users\austi\pycharmprojects\wrap-it\venv\lib\site-packages\dephell\actions\_converting.py", line 7, in <module>
    from ..converters import CONVERTERS
  File "c:\users\austi\pycharmprojects\wrap-it\venv\lib\site-packages\dephell\converters\__init__.py", line 5, in <module>
    from .base import BaseConverter
  File "c:\users\austi\pycharmprojects\wrap-it\venv\lib\site-packages\dephell\converters\base.py", line 11, in <module>
    from ..controllers import Graph, Mutator, Resolver
  File "c:\users\austi\pycharmprojects\wrap-it\venv\lib\site-packages\dephell\controllers\__init__.py", line 4, in <module>
    from ._docker import DockerContainer, DockerContainers
  File "c:\users\austi\pycharmprojects\wrap-it\venv\lib\site-packages\dephell\controllers\_docker.py", line 9, in <module>
    import dockerpty
  File "c:\users\austi\pycharmprojects\wrap-it\venv\lib\site-packages\dockerpty\__init__.py", line 17, in <module>
    from dockerpty.pty import PseudoTerminal, RunOperation, ExecOperation, exec_create
  File "c:\users\austi\pycharmprojects\wrap-it\venv\lib\site-packages\dockerpty\pty.py", line 22, in <module>
    import dockerpty.io as io
  File "c:\users\austi\pycharmprojects\wrap-it\venv\lib\site-packages\dockerpty\io.py", line 18, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

**Comment by austinv11** [comment]
Is it possible to at least disable the docker commands?

**Comment by orsinium** [comment]
Thank you for the issue!

> Dephell installs perfectly fine

I don't think it will work, sorry. Windows support on the way. All `dephell_*` packages are tested for windows support, but not dephell itself.

> The full traceback is below but its because dockerpty requires the stdlib module fnctl which is not available on windows.

I think you can try to poke https://github.com/d11wtq/dockerpty/issues/7 . Or even contribute a solution from https://github.com/cs01/gdbgui/issues/18

> Is it possible to at least disable the docker commands?

You always can just remove the command from the source files, but as I said you'll face something else eventually, and it requires to dive deeper and fix much more. Of course, if you're really interested in it, I'll be happy to accept PRs.

This particular issue is about dependency, so I close it.

**Comment by dmwyatt** [comment]
@orsinium To make sure we're clear, dephell doesn't work on Windows?

Maybe a note about this is needed in README.md...

**Comment by jed-frey** [comment]
Definitely a notice in the ReadMe for those of us unable to breakfree of Windows at work.
