### ISSUE TITLE
TypeError: attrs() got an unexpected keyword argument 'eq'

### ISSUE THREAD

**Issue by jayvdb** [dephell/dephell#286]
pyproject.toml includes `attrs = ">=19.1.0"` and I have 19.1.0 installed, yet:
```py
dephell> python3 -m dephell deps convert
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jayvdb/projects/dephell/dephell/dephell/__main__.py", line 2, in <module>
    from .cli import entrypoint
  File "/home/jayvdb/projects/dephell/dephell/dephell/cli.py", line 10, in <module>
    from .commands import COMMANDS
  File "/home/jayvdb/projects/dephell/dephell/dephell/commands/__init__.py", line 2, in <module>
    from .discover import COMMANDS
  File "/home/jayvdb/projects/dephell/dephell/dephell/commands/discover.py", line 73, in <module>
    module = import_module('.' + module_name, package=package)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/jayvdb/projects/dephell/dephell/dephell/commands/auth.py", line 10, in <module>
    from .base import BaseCommand
  File "/home/jayvdb/projects/dephell/dephell/dephell/commands/base.py", line 14, in <module>
    from ..actions import attach_deps, get_python_env
  File "/home/jayvdb/projects/dephell/dephell/dephell/actions/__init__.py", line 6, in <module>
    from ._converting import attach_deps
  File "/home/jayvdb/projects/dephell/dephell/dephell/actions/_converting.py", line 7, in <module>
    from ..converters import CONVERTERS
  File "/home/jayvdb/projects/dephell/dephell/dephell/converters/__init__.py", line 5, in <module>
    from .base import BaseConverter
  File "/home/jayvdb/projects/dephell/dephell/dephell/converters/base.py", line 11, in <module>
    from ..controllers import Graph, Mutator, Resolver
  File "/home/jayvdb/projects/dephell/dephell/dephell/controllers/__init__.py", line 3, in <module>
    from ._dependency import DependencyMaker
  File "/home/jayvdb/projects/dephell/dephell/dephell/controllers/_dependency.py", line 14, in <module>
    from ..models.constraint import Constraint
  File "/home/jayvdb/projects/dephell/dephell/dephell/models/__init__.py", line 2, in <module>
    from .auth import Auth
  File "/home/jayvdb/projects/dephell/dephell/dephell/models/auth.py", line 10, in <module>
    @attr.s(eq=True, order=True, frozen=True)
TypeError: attrs() got an unexpected keyword argument 'eq'
```

Upgrading to attrs-19.3.0 fixed the problem.

**Comment by orsinium** [comment]
Oh, right

> New in version 19.2.0: eq and order
https://www.attrs.org/en/stable/api.html#attr.s

Thank you :+1:

**Comment by kevinastone** [comment]
Any chance you could release an updated version that includes this fix?  It's currently broken on the latest release (`v0.7.5`).

**Comment by orsinium** [comment]
The fix doesn't introduce compatibility with old version of attrs. It changes dephell's requirements. So, update attrs in the dephell's environment, and everything will be ok

**Comment by kevinastone** [comment]
I understand it's not backwards compatible, I just want the version constraint updated so that pip correctly pulls in `attrs>=19.2`.  Otherwise, I have to manually manage the virtualenv.

**Comment by orsinium** [comment]
That's strange, pip should install the latest version of attrs by default. Anyway, we'll release it very soon, with [dephell_setuptools](https://github.com/dephell/dephell_setuptools) integration. Thank you for your feedback :)
