### ISSUE TITLE
Do not work dephell installed by install.py

### ISSUE THREAD

**Issue by 515hikaru** [dephell/dephell#304]
### Description

If you install as described in README, dephell will not work.

I faced this trouble in Ubuntu 18.04 and Python 3.7.4.

### Steps to Reproduce

1. `curl -L dephell.org/install | python3`
2. exec `dephell`
3. An error occurs: `ValueError: unsupported pickle protocol: 5`

**Expected behavior:**

* `dephell` works correctly.

**Actual behavior:**

```
$ dephell
Traceback (most recent call last):
  File "/home/hikaru/.local/bin/dephell", line 5, in <module>
    from dephell.cli import entrypoint
  File "/home/hikaru/.local/share/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/cli.py", line 10, in <module>
    from .commands import COMMANDS
  File "/home/hikaru/.local/share/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/commands/__init__.py", line 2, in <module>
    from .discover import COMMANDS
  File "/home/hikaru/.local/share/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/commands/discover.py", line 73, in <module>
    module = import_module('.' + module_name, package=package)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/hikaru/.local/share/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/commands/auth.py", line 10, in <module>
    from .base import BaseCommand
  File "/home/hikaru/.local/share/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/commands/base.py", line 14, in <module>
    from ..actions import attach_deps, get_python_env
  File "/home/hikaru/.local/share/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/actions/__init__.py", line 17, in <module>
    from ._transform import transform_imports
  File "/home/hikaru/.local/share/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/actions/_transform.py", line 2, in <module>
    from bowler import LN, Capture, Filename, Query
  File "/home/hikaru/.local/share/dephell/venvs/dephell/lib/python3.7/site-packages/bowler/__init__.py", line 13, in <module>
    from .imr import FunctionArgument, FunctionSpec
  File "/home/hikaru/.local/share/dephell/venvs/dephell/lib/python3.7/site-packages/bowler/imr.py", line 12, in <module>
    from fissix.fixer_util import LParen, Name
  File "/home/hikaru/.local/share/dephell/venvs/dephell/lib/python3.7/site-packages/fissix/fixer_util.py", line 7, in <module>
    from .pygram import python_symbols as syms
  File "/home/hikaru/.local/share/dephell/venvs/dephell/lib/python3.7/site-packages/fissix/pygram.py", line 30, in <module>
    python_grammar = driver.load_packaged_grammar("fissix", _GRAMMAR_FILE)
  File "/home/hikaru/.local/share/dephell/venvs/dephell/lib/python3.7/site-packages/fissix/pgen2/driver.py", line 153, in load_packaged_grammar
    return load_grammar(grammar_source)
  File "/home/hikaru/.local/share/dephell/venvs/dephell/lib/python3.7/site-packages/fissix/pgen2/driver.py", line 128, in load_grammar
    g.load(gp)
  File "/home/hikaru/.local/share/dephell/venvs/dephell/lib/python3.7/site-packages/fissix/pgen2/grammar.py", line 95, in load
    d = pickle.load(f)
ValueError: unsupported pickle protocol: 5
```

### Workaround

I found a workaround. The error occurs in fissix package. Its version is 19.2b1.

I tried to downgrade the package.

```
$ source ~/.local/share/dephell/venvs/dephell/bin/activate
$ pip freeze | grep fissix
fissix==19.2b1
$ pip install fissix==19.1b1
```

And exec `dephell`, it works normally.

**Comment by 515hikaru** [comment]
I tried again today and it was successful with no problems even though dephell uses fissix==19.2b1.

I don't know the cause, but I can't reproduce it because it doesn't happen in my environment, so this issue is closed.
