### ISSUE TITLE
Unable to parse some requirements

### ISSUE THREAD

**Issue by AnOctopus** [dephell/dephell#305]
### Required Information

Please attach the output of the following commands

* [x] Output of failing Dephell command with `--traceback` and `--level=DEBUG` flags set
```
(python) [awalker@awalker-xps 0 python]$ dephell deps install --traceback --level=DEBUG --from requirements.txt         
WARNING cannot find config file 
INFO get dependencies (format=pip, path=requirements.txt)
INFO build dependencies graph... 
ERROR ValueError: cannot parse requirement: proto-google-cloud-error-reporting-v1beta1[grpc][grpc]<0.16dev,>=0.15.3 from gapic-google-cloud-error-reporting-v1beta1 0.15.3 
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3.7/site-packages/pyparsing.py", line 1939, in parseString
    raise exc
  File "/usr/lib/python3.7/site-packages/pyparsing.py", line 1929, in parseString
    loc, tokens = self._parse(instring, 0)
  File "/usr/lib/python3.7/site-packages/pyparsing.py", line 1669, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/usr/lib/python3.7/site-packages/pyparsing.py", line 4037, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/usr/lib/python3.7/site-packages/pyparsing.py", line 1673, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/usr/lib/python3.7/site-packages/pyparsing.py", line 3783, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected stringEnd, found '['  (at char 48), (line:1, col:49)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dephell/repositories/_warehouse/_base.py", line 53, in _convert_deps
    req = Requirement(dep)
  File "/usr/lib/python3.7/site-packages/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc : e.loc + 8], e.msg
packaging.requirements.InvalidRequirement: Parse error at "'[grpc]<0'": Expected stringEnd

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dephell/cli.py", line 79, in main
    result = task()
  File "/usr/lib/python3.7/site-packages/dephell/commands/deps_install.py", line 33, in __call__
    resolver = self._get_locked(default_envs={'main'})
  File "/usr/lib/python3.7/site-packages/dephell/commands/base.py", line 125, in _get_locked
    return self._resolve(resolver=resolver, default_envs=default_envs)
  File "/usr/lib/python3.7/site-packages/dephell/commands/base.py", line 131, in _resolve
    resolved = resolver.resolve(silent=self.config['silent'])
  File "/usr/lib/python3.7/site-packages/dephell/controllers/_resolver.py", line 86, in resolve
    resolved = self._resolve(debug=debug, silent=silent, level=level, spinner=spinner)
  File "/usr/lib/python3.7/site-packages/dephell/controllers/_resolver.py", line 113, in _resolve
    no_conflicts = self._apply_deps(deps, debug=debug)
  File "/usr/lib/python3.7/site-packages/dephell/controllers/_resolver.py", line 190, in _apply_deps
    conflict = self.apply(dep)
  File "/usr/lib/python3.7/site-packages/dephell/controllers/_resolver.py", line 49, in apply
    if not other_dep.compat:
  File "/usr/lib/python3.7/site-packages/dephell/models/dependency.py", line 154, in compat
    for group in self.groups:
  File "/usr/lib/python3.7/site-packages/dephell/models/groups.py", line 170, in __iter__
    self._load_release_deps(release)
  File "/usr/lib/python3.7/site-packages/dephell/models/groups.py", line 149, in _load_release_deps
    release.dependencies = loop.run_until_complete(gathered)[0]
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/usr/lib/python3.7/site-packages/dephell/controllers/_repos.py", line 146, in get_dependencies
    return await repo.get_dependencies(name=name, version=version, extra=extra)
  File "/usr/lib/python3.7/site-packages/dephell/repositories/_warehouse/_api.py", line 141, in get_dependencies
    return self._convert_deps(deps=deps, name=name, version=version, extra=extra)
  File "/usr/lib/python3.7/site-packages/dephell/repositories/_warehouse/_base.py", line 60, in _convert_deps
    raise ValueError(msg.format(dep, name, version)) from e
ValueError: cannot parse requirement: proto-google-cloud-error-reporting-v1beta1[grpc][grpc]<0.16dev,>=0.15.3 from gapic-google-cloud-error-reporting-v1beta1 0.15.3
```

* [x] Project's current Dephell config
None
* [x] Output of `dephell inspect self`
```
WARNING cannot find config file 
{
  "cache": "14.59Mb",
  "path": "/usr/lib/python3.7/site-packages/dephell",
  "python": "/usr/bin/python",
  "version": "0.7.7",
  "versions": {}
}
```

### Description

Some packages fail to be parsed by dephell when they are included as project dependencies. I have seen this happen with dependencies from both `requirement.txt` files and poetry configs.
`proto-google-cloud-error-reporting-v1beta1==0.15.3` is the line that triggered the above error. It prevents dephell from doing anything that requires processing the dependencies.

**Comment by leosussan** [comment]
Having the same issue w/ pipfilelock definition, on Twilio's dependencies:

```
        "twilio": {
            "hashes": [
                "sha256:668c71d17fa1f48137e883c73c6dc56f0c2afeaca5883ad8033384d8c8e6c793"
            ],
            "index": "pypi",
            "version": "==6.33.1"
        },
```

Traceback:

```
ERROR ValueError: cannot parse requirement: requests[security][security]>=2.0.0; python_version < "3.0" from twilio 6.33.1 
Traceback (most recent call last):
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/pyparsing.py", line 1945, in parseString
    raise exc
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/pyparsing.py", line 1935, in parseString
    loc, tokens = self._parse(instring, 0)
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/pyparsing.py", line 1675, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/pyparsing.py", line 4050, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/pyparsing.py", line 1679, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/pyparsing.py", line 3796, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected stringEnd, found '['  (at char 18), (line:1, col:19)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/repositories/_warehouse/_base.py", line 86, in _convert_deps
    req = Requirement(dep)
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc : e.loc + 8], e.msg
packaging.requirements.InvalidRequirement: Parse error at "'[securit'": Expected stringEnd

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/cli.py", line 115, in main
    result = task()
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/commands/deps_install.py", line 33, in __call__
    resolver = self._get_locked(default_envs={'main'})
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/commands/base.py", line 135, in _get_locked
    return self._resolve(resolver=resolver, default_envs=default_envs)
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/commands/base.py", line 141, in _resolve
    resolved = resolver.resolve(silent=self.config['silent'])
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/controllers/_resolver.py", line 86, in resolve
    resolved = self._resolve(debug=debug, silent=silent, level=level, spinner=spinner)
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/controllers/_resolver.py", line 113, in _resolve
    no_conflicts = self._apply_deps(deps, debug=debug)
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/controllers/_resolver.py", line 193, in _apply_deps
    conflict = self.apply(dep)
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/controllers/_resolver.py", line 49, in apply
    if not other_dep.compat:
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/models/dependency.py", line 154, in compat
    for group in self.groups:
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/models/groups.py", line 170, in __iter__
    self._load_release_deps(release)
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/models/groups.py", line 149, in _load_release_deps
    release.dependencies = loop.run_until_complete(gathered)[0]
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/controllers/_repos.py", line 146, in get_dependencies
    return await repo.get_dependencies(name=name, version=version, extra=extra)
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/repositories/_warehouse/_api.py", line 127, in get_dependencies
    return self._convert_deps(deps=deps, name=name, version=version, extra=extra)
  File "/Users/leo/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/repositories/_warehouse/_base.py", line 93, in _convert_deps
    raise ValueError(msg.format(dep, name, version)) from e
ValueError: cannot parse requirement: requests[security][security]>=2.0.0; python_version < "3.0" from twilio 6.33.1
```

**Comment by ebridges** [comment]
I'm getting the same error with `requests-oauthlib`

Using the sample project as follows:

```
git clone https://github.com/pypa/sampleproject.git
rm pyproject.toml
poetry init --name=sample --description='sample project' --author='John Smith <jsmith@example.com>'
[click through prompts]
poetry add requests-oauthlib
source $VIRTUAL_ENV/bin/activate
pip install dephell
dephell deps convert --from-format poetry --from-path pyproject.toml --to-format pip --to-path requirements.txt
```

As the above examples, it looks like it's having a problem with `[xxx][xxx]`?

Any workarounds would be much appreciates!

Thank you!

<details>
<summary><tt>ValueError: cannot parse requirement: oauthlib[signedtoken][signedtoken]>=3.0.0; extra == "rsa" from requests-oauthlib 1.3.0</tt></summary>
<pre>
DEBUG load dependencies... (format=poetry, path=pyproject.toml)
ERROR ValueError: cannot parse requirement: oauthlib[signedtoken][signedtoken]>=3.0.0; extra == "rsa" from requests-oauthlib 1.3.0
Traceback (most recent call last):
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/packaging/requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/pyparsing.py", line 1945, in parseString
    raise exc
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/pyparsing.py", line 1935, in parseString
    loc, tokens = self._parse(instring, 0)
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/pyparsing.py", line 1675, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/pyparsing.py", line 4050, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/pyparsing.py", line 1679, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/pyparsing.py", line 3796, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected stringEnd, found '['  (at char 21), (line:1, col:22)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/dephell/repositories/_warehouse/_base.py", line 86, in _convert_deps
    req = Requirement(dep)
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/packaging/requirements.py", line 97, in __init__
    requirement_string[e.loc : e.loc + 8], e.msg
packaging.requirements.InvalidRequirement: Parse error at "'[signedt'": Expected stringEnd

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/dephell/cli.py", line 115, in main
    result = task()
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/dephell/commands/deps_convert.py", line 77, in __call__
    resolver.apply_envs(set(self.config['envs']))
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/dephell/controllers/_resolver.py", line 164, in apply_envs
    self.apply(dep)
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/dephell/controllers/_resolver.py", line 29, in apply
    for new_dep in parent.dependencies:
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/dephell/models/dependency.py", line 86, in dependencies
    for dep in self.group.dependencies:
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/dephell/cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/dephell/models/dependency.py", line 66, in group
    for group in self.groups:
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/dephell/models/groups.py", line 170, in __iter__
    self._load_release_deps(release)
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/dephell/models/groups.py", line 149, in _load_release_deps
    release.dependencies = loop.run_until_complete(gathered)[0]
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/dephell/controllers/_repos.py", line 146, in get_dependencies
    return await repo.get_dependencies(name=name, version=version, extra=extra)
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/dephell/repositories/_warehouse/_api.py", line 127, in get_dependencies
    return self._convert_deps(deps=deps, name=name, version=version, extra=extra)
  File "/Users/ebridges/Library/Caches/pypoetry/virtualenvs/sample-py3.7/lib/python3.7/site-packages/dephell/repositories/_warehouse/_base.py", line 93, in _convert_deps
    raise ValueError(msg.format(dep, name, version)) from e
ValueError: cannot parse requirement: oauthlib[signedtoken][signedtoken]>=3.0.0; extra == "rsa" from requests-oauthlib 1.3.0
</pre>
</details>

**Comment by orsinium** [comment]
@AnOctopus, please, update Dephell. The latest release **0.7.9**. I'm not sure that it helps but I definitely fixed something like this in some release. Let's talk about the latest one.

@ebridges thank you for steps to reproduce. However, I've tried it and it works for me. Could you attach `dephell inspect self` output as well?

@leosussan is it OSS? Could you make a small sample to reproduce the issue, please?

**Comment by last-partizan** [comment]
@orsinium 
I have dephell version 0.7.9 and minimal reproducible steps:

```
> dephell inspect self
WARNING cannot find config file 
{
  "cache": "21.88Mb",
  "path": "/usr/lib/python3.8/site-packages/dephell",
  "python": "/usr/bin/python",
  "version": "0.7.9",
  "versions": {}
}
> mkdir test && cd test
> pipenv install twilio
> dephell deps install --from=Pipfile.lock
WARNING cannot find config file 
INFO get dependencies (format=pipfilelock, path=Pipfile.lock)
INFO build dependencies graph... 
ERROR ValueError: cannot parse requirement: requests[security][security]>=2.0.0; python_version < "3.0" from twilio 6.35.0 
```

**Comment by orsinium** [comment]
Great! I've caught it! Thank you, @last-partizan. I'll take care of the fix.
