### ISSUE TITLE
should be 'join' instead of 'hoin.

### ISSUE THREAD

**Issue by rvanlaar** [dephell/dephell#326]
https://github.com/dephell/dephell/blob/d98fa2130c33f678ff22930538ddda0ebdb20e13/dephell/actions/_package.py#L12

```
dephell deps audit --traceback --filter="#.links.flatten()" jinja2==2.0
WARNING cannot find config file 
ERROR AttributeError: 'str' object has no attribute 'hoin' 
Traceback (most recent call last):
  File "/home/roland/.local/lib/python3.7/site-packages/dephell/cli.py", line 115, in main
    result = task()
  File "/home/roland/.local/lib/python3.7/site-packages/dephell/commands/deps_audit.py", line 30, in __call__
    packages = get_packages(reqs=self.args.name)
  File "/home/roland/.local/lib/python3.7/site-packages/dephell/actions/_package.py", line 12, in get_packages
    root = PIPConverter(lock=False).loads('\n'.hoin(reqs))
AttributeError: 'str' object has no attribute 'hoin'
```

**Comment by 515hikaru** [comment]
Thank you for your report. I submitted PR # 328.
