### ISSUE TITLE
dephell -h commands fails

### ISSUE THREAD

**Issue by iamsauravsharma** [dephell/dephell#358]
## Short description
When `dephell -h` command is ran then it fails with error AttributeError: 'NoneType' object has no attribute 'split'

## Output

dephell -h should print same output as dephell --help ( which is not failing)
```
Traceback (most recent call last):
  File "/home/saurav/.local/bin/dephell", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/saurav/.local/share/dephell/venvs/dephell/lib/python3.8/site-packages/dephell/cli.py", line 82, in entrypoint
    exit(main(argv[1:]))
  File "/home/saurav/.local/share/dephell/venvs/dephell/lib/python3.8/site-packages/dephell/cli.py", line 42, in main
    parser._print_message(parser.format_help(command=command))
  File "/home/saurav/.local/share/dephell/venvs/dephell/lib/python3.8/site-packages/dephell_argparse/_parser.py", line 163, in format_help
    self._format_commands(formatter=formatter, command=command)
  File "/home/saurav/.local/share/dephell/venvs/dephell/lib/python3.8/site-packages/dephell_argparse/_parser.py", line 183, in _format_commands
    elif command.guesses:
  File "/home/saurav/.local/share/dephell/venvs/dephell/lib/python3.8/site-packages/dephell_argparse/_cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/saurav/.local/share/dephell/venvs/dephell/lib/python3.8/site-packages/dephell_argparse/_command.py", line 85, in guesses
    for name in self.argv[:2]:
  File "/home/saurav/.local/share/dephell/venvs/dephell/lib/python3.8/site-packages/dephell_argparse/_command.py", line 29, in argv
    return self._argv[self.words:]
  File "/home/saurav/.local/share/dephell/venvs/dephell/lib/python3.8/site-packages/dephell_argparse/_cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/saurav/.local/share/dephell/venvs/dephell/lib/python3.8/site-packages/dephell_argparse/_command.py", line 25, in words
    return len(self.match.split())
AttributeError: 'NoneType' object has no attribute 'split'
```

## Steps to reproduce

```bash
$ dephell -h
```

# Versions
```json
{
  "cache": "0b",
  "path": "/home/saurav/.local/share/dephell/venvs/dephell/lib/python3.8/site-packages/dephell",
  "python": "/home/saurav/.local/share/dephell/venvs/dephell/bin/python3",
  "version": "0.8.0",
  "versions": {
    "dephell-archive": "0.1.6",
    "dephell-discover": "0.2.10",
    "dephell-licenses": "0.1.6",
    "dephell-links": "0.1.5",
    "dephell-markers": "1.0.3",
    "dephell-pythons": "0.1.14",
    "dephell-shells": "0.1.4",
    "dephell-specifier": "0.2.1",
    "dephell-venvs": "0.1.17",
    "dephell-versioning": "0.1.1"
  }
}
```

**Comment by jhermann** [comment]
A quick fix is `return len((self.match or '').split())`.

**Comment by orsinium** [comment]
Thank you! I will transfer it in the right repo.
