### ISSUE TITLE
Unable to create a poetry.lock file -- Lookup Error All dependencies are empty

### ISSUE THREAD

**Issue by timothyjlaurent** [dephell/dephell#377]
## Short description

When trying to generate a poetry.lock file with the cli fails with an error. I'm able to generate setup.py from pyproject.toml though.

## Output

```
dephell deps convert --from=pyproject.toml --to=poetry.lock
WARNING cannot find tool.dephell section in the config (path=pyproject.toml)
ERROR LookupError: all dependencies are empty 
```

## Steps to reproduce

pyproject.toml
```toml
[tool.poetry]
name = "someproject"
version = "0.1.0"
description = ""
authors = ["me@me.me"]
packages = []

[tool.poetry.dependencies]
python = "^3.6"
attrs = "^19.1"
cattrs = "^0.9.0"
bidict = "^0.18.2"
gensim = "^3.8.0"
h5py = "^2.10.0"
jsonlines = "^1.2.0"
more-itertools = "^7.2"
python-rapidjson = "^0.8.0"
scikit-learn = "^0.21.3"
scipy = "^1.3.2"
seqeval = "^0.0.12"
spacy = "^2.2.3"
sty = {version = "^1.0-beta.1", allows-prereleases = true}
subword-nmt = "^0.3.6"
tensorflow-gpu = { version = "^2.0.0", optional = true }
tensorflow-determinism = { version = "^0.3.0", optional = true }
tensorflow = { version = "^2.0.0", optional = true }
typing_extensions = "^3.7.4"
tabulate = "^0.8.0"
tqdm = "^4.36.0"
pandas = "^0.25.0"
beautifulsoup4 = "^4.8"
click = "^7.0"

[tool.poetry.extras]
tf-cpu = ["tensorflow"]
tf-gpu = ["tensorflow-gpu", "tensorflow-determinism"]

[tool.poetry.dev-dependencies]
pre-commit = "^1.20"
pytest = "^5"
pytest-cov = "^2.8.1"
hypothesis = "^4.44.2"

```

## Traceback

```
Traceback (most recent call last):
  File "/Users/timothy.laurent/.virtualenvs/inv-text2struct/lib/python3.7/site-packages/dephell/cli.py", line 64, in main
    result = handler()
  File "/Users/timothy.laurent/.virtualenvs/inv-text2struct/lib/python3.7/site-packages/dephell/commands/deps_convert.py", line 92, in __call__
    dumper.dump(path=self.config['to']['path'], **dumper_kwargs)
  File "/Users/timothy.laurent/.virtualenvs/inv-text2struct/lib/python3.7/site-packages/dephell/converters/base.py", line 74, in dump
    content = self.dumps(reqs=reqs, content=content, project=project)
  File "/Users/timothy.laurent/.virtualenvs/inv-text2struct/lib/python3.7/site-packages/dephell/converters/poetrylock.py", line 70, in dumps
    doc['package'] = [self._format_req(req=req) for req in reqs]
  File "/Users/timothy.laurent/.virtualenvs/inv-text2struct/lib/python3.7/site-packages/dephell/converters/poetrylock.py", line 70, in <listcomp>
    doc['package'] = [self._format_req(req=req) for req in reqs]
  File "/Users/timothy.laurent/.virtualenvs/inv-text2struct/lib/python3.7/site-packages/dephell/converters/poetrylock.py", line 223, in _format_req
    deps = req.dep.dependencies
  File "/Users/timothy.laurent/.virtualenvs/inv-text2struct/lib/python3.7/site-packages/dephell/models/dependency.py", line 86, in dependencies
    for dep in self.group.dependencies:
  File "/Users/timothy.laurent/.virtualenvs/inv-text2struct/lib/python3.7/site-packages/dephell/cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/timothy.laurent/.virtualenvs/inv-text2struct/lib/python3.7/site-packages/dephell/models/dependency.py", line 69, in group
    raise LookupError('all dependencies are empty')
LookupError: all dependencies are empty

```

## Config
See above

# Versions

```json
{
  "cache": "4.47Mb",
  "path": "/Users/timothy.laurent/.virtualenvs/inv-text2struct/lib/python3.7/site-packages/dephell",
  "python": "/Users/timothy.laurent/.virtualenvs/inv-text2struct/bin/python",
  "version": "0.8.1",
  "versions": {
    "dephell-archive": "0.1.6",
    "dephell-argparse": "0.1.2",
    "dephell-changelogs": "0.0.1",
    "dephell-discover": "0.2.10",
    "dephell-licenses": "0.1.6",
    "dephell-links": "0.1.5",
    "dephell-markers": "1.0.3",
    "dephell-pythons": "0.1.14",
    "dephell-setuptools": "0.2.3",
    "dephell-shells": "0.1.4",
    "dephell-specifier": "0.2.1",
    "dephell-venvs": "0.1.17",
    "dephell-versioning": "0.1.1"
  }
}

```

**Comment by Viginox** [comment]
This seems to be an issue with (at least) dephell version **0.8.1** and **0.8.2**.
In version **0.8.3** (the current version), this issue is not present anymore.

Therefore, this issue might be closed.
