### ISSUE TITLE
RFE: --no-network

### ISSUE THREAD

**Issue by mcepl** [dephell/dephell#414]
## Short description

When trying to run
```sh
dephell deps convert --from pyproject.toml --to setup.py
```
inside of the building scripts for openSUSE packaging (because sometimes ``pyproject.toml``-based tools are just not stable yet enough).

Unfortunately, there is absolutely no network access inside of the build systems (for obvious security reasons), so every run of the scripts fails.

What I would like to get was the option ``--no-network`` (or something like that), which would cause dephell whenever it really needs some resource which is not installed in the system, just print the error message with the missing resources and failed.

## Output

```
[    8s] + dephell deps convert --traceback --level=DEBUG --from pyproject.toml --to setup.py
[    9s] DEBUG load dependencies... (format=flit, path=pyproject.toml)
[    9s] ERROR ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/requests/json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f15bb39f0d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')) 
[    9s] Traceback (most recent call last):
[    9s]   File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn
[    9s]     conn = connection.create_connection(
[    9s]   File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
[    9s]     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
[    9s]   File "/usr/lib64/python3.8/socket.py", line 918, in getaddrinfo
[    9s]     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
[    9s] socket.gaierror: [Errno -3] Temporary failure in name resolution
[    9s] 
[    9s] During handling of the above exception, another exception occurred:
[    9s] 
[    9s] Traceback (most recent call last):
[    9s]   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
[    9s]     httplib_response = self._make_request(
[    9s]   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
[    9s]     self._validate_conn(conn)
[    9s]   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
[    9s]     conn.connect()
[    9s]   File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 300, in connect
[    9s]     conn = self._new_conn()
[    9s]   File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn
[    9s]     raise NewConnectionError(
[    9s] urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f15bb39f0d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
[    9s] 
[    9s] During handling of the above exception, another exception occurred:
[    9s] 
[    9s] Traceback (most recent call last):
[    9s]   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
[    9s]     resp = conn.urlopen(
[    9s]   File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
[    9s]     retries = retries.increment(
[    9s]   File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
[    9s]     raise MaxRetryError(_pool, url, error or ResponseError(cause))
[    9s] urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/requests/json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f15bb39f0d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[    9s] 
[    9s] During handling of the above exception, another exception occurred:
[    9s] 
[    9s] Traceback (most recent call last):
[    9s]   File "/usr/lib/python3.8/site-packages/dephell/cli.py", line 64, in main
[    9s]     result = handler()
[    9s]   File "/usr/lib/python3.8/site-packages/dephell/commands/deps_convert.py", line 76, in __call__
[    9s]     resolver.apply_envs(set(self.config['envs']))
[    9s]   File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 166, in apply_envs
[    9s]     self.apply(dep)
[    9s]   File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 29, in apply
[    9s]     for new_dep in parent.dependencies:
[    9s]   File "/usr/lib/python3.8/site-packages/dephell/models/dependency.py", line 86, in dependencies
[    9s]     for dep in self.group.dependencies:
[    9s]   File "/usr/lib/python3.8/site-packages/dephell/cached_property.py", line 18, in __get__
[    9s]     value = obj.__dict__[self.func.__name__] = self.func(obj)
[    9s]   File "/usr/lib/python3.8/site-packages/dephell/models/dependency.py", line 66, in group
[    9s]     for group in self.groups:
[    9s]   File "/usr/lib/python3.8/site-packages/dephell/models/groups.py", line 169, in __iter__
[    9s]     release = self.releases[0]
[    9s]   File "/usr/lib/python3.8/site-packages/dephell/cached_property.py", line 18, in __get__
[    9s]     value = obj.__dict__[self.func.__name__] = self.func(obj)
[    9s]   File "/usr/lib/python3.8/site-packages/dephell/models/groups.py", line 34, in releases
[    9s]     releases = self.dep.repo.get_releases(self.dep)
[    9s]   File "/usr/lib/python3.8/site-packages/dephell/controllers/_repos.py", line 138, in get_releases
[    9s]     return repo.get_releases(dep=dep)
[    9s]   File "/usr/lib/python3.8/site-packages/dephell/repositories/_warehouse/_api.py", line 75, in get_releases
[    9s]     response = session.get(url, auth=self.auth)
[    9s]   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
[    9s]     return self.request('GET', url, **kwargs)
[    9s]   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
[    9s]     resp = self.send(prep, **send_kwargs)
[    9s]   File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
[    9s]     r = adapter.send(request, **kwargs)
[    9s]   File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
[    9s]     raise ConnectionError(e, request=request)
[    9s] requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/requests/json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f15bb39f0d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[    9s] error: Bad exit status from /var/tmp/rpm-tmp.Z2jJpN (%prep)
[    9s] 
[    9s] 
[    9s] RPM build errors:
[    9s]     Bad exit status from /var/tmp/rpm-tmp.Z2jJpN (%prep)
[    9s] 
[    9s] stitny failed "build python-dephell_changelogs.spec" at Mon Mar 23 23:15:33 UTC 2020.
[    9s]
```

## Steps to reproduce

See above: run ``dephell deps convert`` in the openSUSE Build System.

## Config

This was ``pyproject.toml`` from ``dephell_changelog`` package.

# Versions

```json
{
  "cache": "0b",
  "path": "/usr/lib/python3.8/site-packages/dephell",
  "python": "/usr/bin/python3",
  "version": "0.8.1",
  "versions": {
    "dephell-archive": "0.1.6",
    "dephell-argparse": "0.1.2",
    "dephell-changelogs": "0.0.1",
    "dephell-discover": "0.2.10",
    "dephell-licenses": "0.1.6",
    "dephell-links": "0.1.5",
    "dephell-markers": "1.0.3",
    "dephell-pythons": "0.1.14",
    "dephell-setuptools": "0.2.3",
    "dephell-shells": "0.1.4",
    "dephell-specifier": "0.2.1",
    "dephell-venvs": "0.1.17",
    "dephell-versioning": "0.1.1"
  }
}
```

**Comment by Conan-Kudo** [comment]
@mcepl Why do you think this would help any? `dephell` converts projects across tools, those tools may or may not have the ability to do something like that (most don't).

**Comment by mcepl** [comment]
I am sorry, but I really don't understand what you are saying. My RFE was to make ``dephell deps convert`` working in the environment where network is not available. What’s so difficult to understand?

**Comment by orsinium** [comment]
Thank you for your feedback. I think the problem isn't a missed flag to forbid network requests but that it tries to do so when it's possible to avoid it. Let me see what we can do to not make network requests here.
