### ISSUE TITLE
ERROR InvalidRequirement: Parse error at "','": Expected stringEnd

### ISSUE THREAD

**Issue by malthejorgensen** [dephell/dephell#416]
## Short description
_I believe this is an error not directly solvable by dephell, so the issue can perhaps be closed immediately._

_That being said, I'm still adding the issue for searchability – so that people who stumble upon similar errors later can find these notes._

Package versions that have invalid metadata in PyPI will raise the error below or a similar error.
An example of such a package version is `boto3` version `1.2.0` (see https://github.com/boto/boto3/issues/2366).

I have found no resolution for this (e.g. using `--strategy=max` doesn't help).

## Output

    ERROR InvalidRequirement: Parse error at "','": Expected stringEnd

## Steps to reproduce
Using `dephell` on a `Pipfile.lock`-file that has `boto3` version `1.10.50` in it will fail with the error above.

Command to trigger the error:

    # in an empty directory
    pipenv install 'boto3==1.10.*'
    dephell uncache
    dephell deps convert --from-format=pipfilelock --from-path=Pipfile.lock --to-format=poetrylock --to-path=poetry.lock

## Traceback

```
Traceback (most recent call last):
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/packaging/requirements.py", line 98, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/pyparsing.py", line 1947, in parseString
    raise exc
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/pyparsing.py", line 1937, in parseString
    loc, tokens = self._parse(instring, 0)
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/pyparsing.py", line 4052, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/pyparsing.py", line 1681, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/pyparsing.py", line 3798, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected stringEnd, found ','  (at char 23), (line:1, col:24)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/cli.py", line 66, in main
    result = handler()
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/commands/deps_convert.py", line 92, in __call__
    dumper.dump(path=self.config['to']['path'], **dumper_kwargs)
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/converters/base.py", line 74, in dump
    content = self.dumps(reqs=reqs, content=content, project=project)
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/converters/poetrylock.py", line 70, in dumps
    doc['package'] = [self._format_req(req=req) for req in reqs]
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/converters/poetrylock.py", line 70, in <listcomp>
    doc['package'] = [self._format_req(req=req) for req in reqs]
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/converters/poetrylock.py", line 223, in _format_req
    deps = req.dep.dependencies
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/models/dependency.py", line 86, in dependencies
    for dep in self.group.dependencies:
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/models/dependency.py", line 66, in group
    for group in self.groups:
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/models/groups.py", line 175, in __iter__
    loop.run_until_complete(future)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/models/groups.py", line 105, in _fetch_releases_deps
    if releases is None:
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/models/groups.py", line 100, in _fetch_missed_deps
    asyncio.ensure_future(self._fetch_missed_deps(releases[center:-1])),
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/models/groups.py", line 100, in _fetch_missed_deps
    asyncio.ensure_future(self._fetch_missed_deps(releases[center:-1])),
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/models/groups.py", line 100, in _fetch_missed_deps
    asyncio.ensure_future(self._fetch_missed_deps(releases[center:-1])),
  [Previous line repeated 2 more times]
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/models/groups.py", line 86, in _fetch_missed_deps
    responses = await asyncio.gather(*tasks)
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/controllers/_repos.py", line 148, in get_dependencies
    return await repo.get_dependencies(name=name, version=version, extra=extra)
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/repositories/_warehouse/_api.py", line 122, in get_dependencies
    deps = await asyncio.gather(asyncio.ensure_future(task))
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/repositories/_warehouse/_api.py", line 259, in _get_from_json
    return await self._get_from_files(response['urls'])
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/repositories/_warehouse/_api.py", line 292, in _get_from_files
    converter=converter,
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/repositories/_warehouse/_base.py", line 125, in _download_and_parse
    root = converter.load(path)
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/converters/wheel.py", line 62, in load
    return self.load_dir(path)
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/converters/wheel.py", line 79, in load_dir
    root = converter.parse_info(content, urls=urls)
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell/converters/egginfo.py", line 154, in parse_info
    req = PackagingRequirement(req)
  File "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/packaging/requirements.py", line 102, in __init__
    raise InvalidRequirement(
packaging.requirements.InvalidRequirement: Parse error at "','": Expected stringEnd
```

## Config

_No config needed_

# Versions

```json
WARNING cannot find config file
{
  "cache": "686.80Kb",
  "path": "/Users/malthe/Library/Application Support/dephell/venvs/dephell/lib/python3.7/site-packages/dephell",
  "python": "/Users/malthe/Library/Application Support/dephell/venvs/dephell/bin/python3",
  "version": "0.8.2",
  "versions": {
    "dephell-archive": "0.1.6",
    "dephell-argparse": "0.1.2",
    "dephell-changelogs": "0.0.1",
    "dephell-discover": "0.2.10",
    "dephell-licenses": "0.1.6",
    "dephell-links": "0.1.5",
    "dephell-markers": "1.0.3",
    "dephell-pythons": "0.1.14",
    "dephell-setuptools": "0.2.3",
    "dephell-shells": "0.1.4",
    "dephell-specifier": "0.2.1",
    "dephell-venvs": "0.1.17",
    "dephell-versioning": "0.1.1"
  }
}
```

**Comment by malthejorgensen** [comment]
A possible fix could be to wrap `req = PackagingRequirement(req)` (dephell/converters/egginfo.py, line 154) in a try/except:

```python
try: 
    req = PackagingRequirement(req)
except InvalidRequirement:
    logger.warn('Skipping %s %s' % (req.raw_name, req.version))
```

The try/except should probably be even further up -- perhaps somewhere around `_fetch_missed_deps()`?

**Comment by orsinium** [comment]
I faced it myself today, they have an incorrect requirements:

```
Requires-Dist: botocore>=1.3.0,<1.4.0',
```

https://pypi.org/project/boto3/1.2.0/#files

Good thinking, I'll have a look at how to wrap it better.
