### ISSUE TITLE
'dephell autocomplete' fails when installing it into pyenv-managed virtualenv

### ISSUE THREAD

**Issue by enchantner** [dephell/dephell#42]
On my development environment I'm using **pyenv**, **pyenv-virtualenv** and **zsh**. So, when I'm doing '_pip install dephell_' inside virtualenv based on pyenv shim and running 'dephell autocomplete' afterwards, it gives me something like "_ERROR: Can't find '/home/meow-nofer/.local/share/pyenv/_dephell_zsh_autocompletion'_".

Okay then, so I installed it without virtualenv, just inside my pyenv's shim. Now I'm getting this:

```~$ dephell autocomplete
Traceback (most recent call last):
  File "/home/meow-nofer/.local/bin/dephell", line 6, in <module>
    from dephell.cli import entrypoint
  File "/home/meow-nofer/.local/lib/python3.7/site-packages/dephell/__init__.py", line 3, in <module>
    from .controllers import *  # noQA
  File "/home/meow-nofer/.local/lib/python3.7/site-packages/dephell/controllers/__init__.py", line 3, in <module>
    from .dependency import DependencyMaker
  File "/home/meow-nofer/.local/lib/python3.7/site-packages/dephell/controllers/dependency.py", line 8, in <module>
    from dephell_links import VCSLink, parse_link
  File "/home/meow-nofer/.local/lib/python3.7/site-packages/dephell_links/__init__.py", line 2, in <module>
    from ._parse import parse_link
  File "/home/meow-nofer/.local/lib/python3.7/site-packages/dephell_links/_parse.py", line 5, in <module>
    from ._vcs import VCSLink
  File "/home/meow-nofer/.local/lib/python3.7/site-packages/dephell_links/_vcs.py", line 9, in <module>
    @attr.s()
AttributeError: module 'attr' has no attribute 's'```

**Comment by orsinium** [comment]
I can't fix the second case: you have installed [attr](https://pypi.org/project/attr/) instead of [attrs](https://pypi.org/project/attrs/), I guess. DepHell's dependencies are OK. Probably, another tool on your system depends on `attr`. Please, let me know if you have more information about it.

Why I think that dependency on attrs is OK:
1. Many other tools depend on attrs. It's already installed on your system.
1. Attrs nice
1. Attrs is zero-dependency project (has no its own dependencies)
1. Attrs quite big to copy-paste this source-code in DepHell's source (like I've done with `cached_property`).

However, I've fixed the first case. Please, update dephell to 0.5.8
