### ISSUE TITLE
deps add does not work

### ISSUE THREAD

**Issue by SwampFalc** [dephell/dephell#421]
New user here, trying to learnt his interesting tool.
However, every time I try a "dephell deps add" I get this error:
```
# dephell deps add --from=pip flake8 --level=DEBUG --traceback
DEBUG merge... 
ERROR KeyError: 'Dependency already added in layer: root' 
Traceback (most recent call last):
  File "/home/ldt/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/cli.py", line 66, in main
    result = handler()
  File "/home/ldt/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/commands/deps_add.py", line 48, in __call__
    resolver.graph.add(new_root)
  File "/home/ldt/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/_graph.py", line 100, in add
    self._layers[0].add(dep)
  File "/home/ldt/.local/share/dephell/venvs/dephell/lib/python3.6/site-packages/dephell/controllers/_graph.py", line 46, in add
    raise KeyError('Dependency already added in layer: ' + dep.name)
KeyError: 'Dependency already added in layer: root'

```
I get the distinct impression that the code that's supposed to merge Layers is simply being skipped...

**Comment by SwampFalc** [comment]
Hmmm... Is it possible that "deps add" only works for poetry, and not for pip, or piplock? I'm not going to test all the possible formats...

**Comment by SwampFalc** [comment]
If you don't mind me re-opening this bug, I saw your merge and I pulled the fix. `deps add` now works for piplock, yes, but at the same time I fear you broke it for poetry (which was working before...)

```
$ dephell deps add --level=DEBUG --traceback --envs dev test -- pytest
DEBUG merge... 
ERROR KeyError: 'cannot find any parent for dependency: pytest' 
Traceback (most recent call last):
  File "/home/ldt/.local/share/dephell/venvs/dephell/github/dephell/cli.py", line 66, in main
    result = handler()
  File "/home/ldt/.local/share/dephell/venvs/dephell/github/dephell/commands/deps_add.py", line 50, in __call__
    resolved = resolver.resolve(level=1, silent=self.config['silent'])
  File "/home/ldt/.local/share/dephell/venvs/dephell/github/dephell/controllers/_resolver.py", line 90, in resolve
    resolved = self._resolve(debug=debug, silent=silent, level=level, spinner=spinner)
  File "/home/ldt/.local/share/dephell/venvs/dephell/github/dephell/controllers/_resolver.py", line 119, in _resolve
    no_conflicts = self._apply_deps(deps, debug=debug)
  File "/home/ldt/.local/share/dephell/venvs/dephell/github/dephell/controllers/_resolver.py", line 208, in _apply_deps
    conflict = self.apply(dep)
  File "/home/ldt/.local/share/dephell/venvs/dephell/github/dephell/controllers/_resolver.py", line 34, in apply
    self.graph.add(other_dep)
  File "/home/ldt/.local/share/dephell/venvs/dephell/github/dephell/controllers/_graph.py", line 118, in add
    raise KeyError('cannot find any parent for dependency: ' + str(dep.name))
KeyError: 'cannot find any parent for dependency: pytest'
```

**Comment by orsinium** [comment]
Thank you for the feedback. Please, open a new one with all fields filled. I cannot reproduce it without the poetry config, the command you listed works for dephell itself.

**Comment by orsinium** [comment]
Nevermind, I've reproduced it with a dependency not in dependency list

```
❯ dephell deps add --level=DEBUG --traceback --envs dev test -- django
DEBUG merge... 
ERROR KeyError: 'cannot find any parent for dependency: django' 
Traceback (most recent call last):
  File "/home/gram/Documents/dephell/dephell/cli.py", line 66, in main
    result = handler()
  File "/home/gram/Documents/dephell/dephell/commands/deps_add.py", line 50, in __call__
    resolved = resolver.resolve(level=1, silent=self.config['silent'])
  File "/home/gram/Documents/dephell/dephell/controllers/_resolver.py", line 90, in resolve
    resolved = self._resolve(debug=debug, silent=silent, level=level, spinner=spinner)
  File "/home/gram/Documents/dephell/dephell/controllers/_resolver.py", line 119, in _resolve
    no_conflicts = self._apply_deps(deps, debug=debug)
  File "/home/gram/Documents/dephell/dephell/controllers/_resolver.py", line 208, in _apply_deps
    conflict = self.apply(dep)
  File "/home/gram/Documents/dephell/dephell/controllers/_resolver.py", line 34, in apply
    self.graph.add(other_dep)
  File "/home/gram/Documents/dephell/dephell/controllers/_graph.py", line 118, in add
    raise KeyError('cannot find any parent for dependency: ' + str(dep.name))
KeyError: 'cannot find any parent for dependency: django'


```

**Comment by mfoglio** [comment]
Hi, I am new to dephell. Is this bug the same reason why I get 
`ERROR KeyError: 'cannot find any parent for dependency: spacy' `
when running `dephell deps add --from=poetry spacy`?
