### ISSUE TITLE
`dephell deps add flake8` not working - `AttributeError: 'ParsedRequirement' object has no attribute 'req'`

### ISSUE THREAD

**Issue by vjpr** [dephell/dephell#433]
## Output

```
AttributeError: 'ParsedRequirement' object has no attribute 'req'
```

When enabling debugging:

```
 dephell deps add --level=DEBUG --traceback cowsay

# This is the `req.__dict__`
{'requirement': 'cowsay', 'is_editable': False, 'comes_from': '-r /var/folders/kp/06ys69nn6hq9k23cv0xxn19m0000gn/T/tmpyvleag9y (line 1)', 'options': {}, 'constraint': False, 'line_source': 'line 1 of /var/folders/kp/06ys69nn6hq9k23cv0xxn19m0000gn/T/tmpyvleag9y'}

ERROR AttributeError: 'ParsedRequirement' object has no attribute 'req'
Traceback (most recent call last):
  File "/Users/Vaughan/.local/lib/python3.8/site-packages/dephell/cli.py", line 66, in main
    result = handler()
  File "/Users/Vaughan/.local/lib/python3.8/site-packages/dephell/commands/deps_add.py", line 39, in __call__
    new_resolver = get_resolver(reqs=self.args.name)
  File "/Users/Vaughan/.local/lib/python3.8/site-packages/dephell/actions/_package.py", line 25, in get_resolver
    resolver = PIPConverter(lock=False).loads_resolver('\n'.join(reqs))
  File "/Users/Vaughan/.local/lib/python3.8/site-packages/dephell/converters/base.py", line 90, in loads_resolver
    root = self.loads(content)
  File "/Users/Vaughan/.local/lib/python3.8/site-packages/dephell/converters/base.py", line 42, in loads
    root = self.load(path=stream.name)
  File "/Users/Vaughan/.local/lib/python3.8/site-packages/dephell/converters/pip.py", line 99, in load
    if req.req is None:

AttributeError: 'ParsedRequirement' object has no attribute 'req'
```

## Steps to reproduce

```
poetry new project
dephell deps add flake8
```

## Traceback

```
...
```

## Config

```toml
[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}


```

# Versions

```json
{
  "cache": "947.48Kb",
  "path": "/Users/Vaughan/.local/lib/python3.8/site-packages/dephell",
  "python": "/Users/Vaughan/.pyenv/versions/3.8.1/bin/python3",
  "version": "0.8.3",
  "versions": {
    "dephell-archive": "0.1.6",
    "dephell-argparse": "0.1.2",
    "dephell-changelogs": "0.0.1",
    "dephell-discover": "0.2.10",
    "dephell-licenses": "0.1.6",
    "dephell-links": "0.1.5",
    "dephell-markers": "1.0.3",
    "dephell-pythons": "0.1.14",
    "dephell-setuptools": "0.2.3",
    "dephell-shells": "0.1.4",
    "dephell-specifier": "0.2.2",
    "dephell-venvs": "0.1.17",
    "dephell-versioning": "0.1.1"
  }
}
```

**Comment by bugchecker** [comment]
Apparently you have 20+ version of pip which incompatible with latest version of the dephell

**Comment by orsinium** [comment]
@bugchecker thank you for your help! That's a good catch.

@vjpr please, install dephell via the official script (or via `pipsi` / `pipx`):
https://dephell.org/

Then it will be isolated and guaranteed to have compatible dependencies.

**Comment by orsinium** [comment]
Feel free to re-open the issue if it didn't help. Thank you!
