### ISSUE TITLE
Depending on pylint + flake8-isort + isort == infinite recursion

### ISSUE THREAD

**Issue by mjpieters** [dephell/dephell#452]
## Short description

Dephell hits an infinite recursion issue when trying to install flake8-isort, pylint and isort together, when all three are un-pinned.

## Output

```$ dephell deps install
INFO get dependencies (format=flit, path=pyproject.toml)
INFO build dependencies graph...
ERROR RecursionError: maximum recursion depth exceeded while getting the str of an object
```

## Steps to reproduce

This can be reproduced with a minimal flit project; given an empty virtualenv, and the following commands:

```bash
$ pip install flit dephell | grep Successfully
Successfully installed dephell-0.8.3 flit-2.3.0
$ touch foobar.py
$ flit init
Module name [foobar]:
Author: Sir Robin
Author email: robin@camelot.uk
Home page: https://github.com/sirrobin/foobar
Choose a license (see http://choosealicense.com/ for more info)
1. MIT - simple and permissive
2. Apache - explicitly grants patent rights
3. GPL - ensures that code based on this is shared with the same terms
4. Skip - choose a license later
Enter 1-4: 4

Written pyproject.toml; edit that file to add optional extra info.
$ cat <<EOF >> pyproject.toml
> requires = [
>     "flake8-isort",
>     "pylint",
>     "isort",
> ]
>
> [tool.dephell.main]
> from = {format = "flit", path = "pyproject.toml"}
> to = {format = "setuppy", path = "setup.py"}
> EOF
$ dephell deps install
INFO get dependencies (format=flit, path=pyproject.toml)
INFO build dependencies graph...
ERROR RecursionError: maximum recursion depth exceeded while getting the str of an object
```

## Traceback

```
INFO get dependencies (format=flit, path=pyproject.toml)
INFO build dependencies graph...
ERROR RecursionError: maximum recursion depth exceeded while getting the str of an object
Traceback (most recent call last):
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/dephell/cli.py", line 66, in main
    result = handler()
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/dephell/commands/deps_install.py", line 32, in __call__
    resolver = self._get_locked(default_envs={'main'})
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/dephell/commands/base.py", line 123, in _get_locked
    return self._resolve(resolver=resolver, default_envs=default_envs)
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/dephell/commands/base.py", line 140, in _resolve
    resolver.apply_envs(default_envs)
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 178, in apply_envs
    self.apply(dep, recursive=True)
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 51, in apply
    self.apply(other_dep, recursive=True)
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 51, in apply
    self.apply(other_dep, recursive=True)
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 51, in apply
    self.apply(other_dep, recursive=True)
  [Previous line repeated 969 more times]
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 45, in apply
    other_dep += new_dep
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/dephell/models/dependency.py", line 241, in __iadd__
    self.groups.actualize()
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/dephell/models/groups.py", line 216, in actualize
    group.releases = filtrate(group.all_releases)
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/dephell/models/constraint.py", line 65, in filter
    if release not in spec:
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/dephell_specifier/range_specifier.py", line 323, in __contains__
    return rule((release in specifier) for specifier in self._specs)
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/dephell_specifier/range_specifier.py", line 323, in <genexpr>
    return rule((release in specifier) for specifier in self._specs)
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/dephell_specifier/specifier.py", line 131, in __contains__
    return self._check_version(version=release.version)
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/dephell_specifier/specifier.py", line 82, in _check_version
    return version in self._semver
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/packaging/specifiers.py", line 204, in __contains__
    return self.contains(item)
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/packaging/specifiers.py", line 226, in contains
    return operator_callable(normalized_item, self.version)
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/packaging/specifiers.py", line 328, in wrapped
    return fn(self, prospective, spec)
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/packaging/specifiers.py", line 532, in _compare_greater_than_equal
    return Version(prospective.public) >= Version(spec)
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/packaging/version.py", line 373, in public
    return str(self).split("+", 1)[0]
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/packaging/version.py", line 314, in __str__
    parts.append(".".join(str(x) for x in self.release))
  File "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/packaging/version.py", line 314, in <genexpr>
    parts.append(".".join(str(x) for x in self.release))
RecursionError: maximum recursion depth exceeded while getting the str of an object
```

## Config

```toml
[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "foobar"
author = "Sir Robin"
author-email = "robin@camelot.uk"
home-page = "https://github.com/sirrobin/foobar"

requires = [
    "flake8-isort",
    "pylint",
    "isort",
]

[tool.dephell.main]
from = {format = "flit", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}
```

# Versions

```json
{
  "cache": "1.55Mb",
  "path": "/Users/mj/.local/pipx/venvs/dephell/lib/python3.8/site-packages/dephell",
  "python": "/Users/mj/.local/pipx/venvs/dephell/bin/python3",
  "version": "0.8.3",
  "versions": {
    "dephell-archive": "0.1.7",
    "dephell-argparse": "0.1.3",
    "dephell-changelogs": "0.0.1",
    "dephell-discover": "0.2.10",
    "dephell-licenses": "0.1.7",
    "dephell-links": "0.1.5",
    "dephell-markers": "1.0.3",
    "dephell-pythons": "0.1.15",
    "dephell-setuptools": "0.2.4",
    "dephell-shells": "0.1.5",
    "dephell-specifier": "0.2.2",
    "dephell-venvs": "0.1.17",
    "dephell-versioning": "0.1.2"
  }
}
```

**Comment by mjpieters** [comment]
The work-around is to restrict `isort` to a version before 5.x:

```toml
requires = [
    "flake8-isort",
    "pylint",
    "isort < 5",
]
```
