### ISSUE TITLE
logging_helpers: TypeError: can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by jayvdb** [dephell/dephell#454]
I have a large pyproject.toml on a commercial project with git+ deps which is failing, and importantly the logging is also failing.  This issue is only about the logging - I'll need to do more analysis to find the root of the other problems.

fwiw, the git hash mentioned refers to https://github.com/viper-development/django-rest-auth/commit/29a24402ad448f1d0d3f0992664d34a5621e0c7a

I doubt that repo is the problem - I assume it could happen to any git+ repo and maybe only if there are network issues of some sort.

```
> dephell deps convert --from-path pyproject.toml --from-format poetry --to-format piplock --to-path requirements.txt
WARNING cannot find tool.dephell section in the config (path=pyproject.toml)
⠋ layers: 1, mutations: 0--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/site-packages/dephell/logging_helpers.py", line 100, in format
    record.msg = Fore.WHITE + record.msg + Fore.RESET
TypeError: can only concatenate str (not "bytes") to str
Call stack:
  File "/usr/bin/dephell", line 11, in <module>
    load_entry_point('dephell==0.8.3', 'console_scripts', 'dephell')()
  File "/usr/lib/python3.8/site-packages/dephell/cli.py", line 84, in entrypoint
    exit(main(argv[1:]))
  File "/usr/lib/python3.8/site-packages/dephell/cli.py", line 66, in main
    result = handler()
  File "/usr/lib/python3.8/site-packages/dephell/commands/deps_convert.py", line 59, in __call__
    resolved = resolver.resolve(silent=self.config['silent'])
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 90, in resolve
    resolved = self._resolve(debug=debug, silent=silent, level=level, spinner=spinner)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 119, in _resolve
    no_conflicts = self._apply_deps(deps, debug=debug)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 208, in _apply_deps
    conflict = self.apply(dep)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 53, in apply
    if not other_dep.compat:
  File "/usr/lib/python3.8/site-packages/dephell/models/dependency.py", line 154, in compat
    for group in self.groups:
  File "/usr/lib/python3.8/site-packages/dephell/models/groups.py", line 173, in __iter__
    if len(self.releases) <= i:
  File "/usr/lib/python3.8/site-packages/dephell/cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/lib/python3.8/site-packages/dephell/models/groups.py", line 37, in releases
    releases = self.dep.repo.get_releases(self.dep)
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 88, in get_releases
    version=self.metaversion,
  File "/usr/lib/python3.8/site-packages/dephell/cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 58, in metaversion
    return self.get_nearest_version(self.link.rev)
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 120, in get_nearest_version
    result = self._call('describe', '--contains', ref)[0]
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 141, in _call
    logger.error(result.stderr)
Message: b"fatal: cannot describe '29a24402ad448f1d0d3f0992664d34a5621e0c7a'\n"
Arguments: ()
⠴ layers: 1, mutations: 0--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/site-packages/dephell/logging_helpers.py", line 100, in format
    record.msg = Fore.WHITE + record.msg + Fore.RESET
TypeError: can only concatenate str (not "bytes") to str
Call stack:
  File "/usr/bin/dephell", line 11, in <module>
    load_entry_point('dephell==0.8.3', 'console_scripts', 'dephell')()
  File "/usr/lib/python3.8/site-packages/dephell/cli.py", line 84, in entrypoint
    exit(main(argv[1:]))
  File "/usr/lib/python3.8/site-packages/dephell/cli.py", line 66, in main
    result = handler()
  File "/usr/lib/python3.8/site-packages/dephell/commands/deps_convert.py", line 59, in __call__
    resolved = resolver.resolve(silent=self.config['silent'])
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 90, in resolve
    resolved = self._resolve(debug=debug, silent=silent, level=level, spinner=spinner)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 119, in _resolve
    no_conflicts = self._apply_deps(deps, debug=debug)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 208, in _apply_deps
    conflict = self.apply(dep)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 53, in apply
    if not other_dep.compat:
  File "/usr/lib/python3.8/site-packages/dephell/models/dependency.py", line 154, in compat
    for group in self.groups:
  File "/usr/lib/python3.8/site-packages/dephell/models/groups.py", line 173, in __iter__
    if len(self.releases) <= i:
  File "/usr/lib/python3.8/site-packages/dephell/cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/lib/python3.8/site-packages/dephell/models/groups.py", line 37, in releases
    releases = self.dep.repo.get_releases(self.dep)
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 88, in get_releases
    version=self.metaversion,
  File "/usr/lib/python3.8/site-packages/dephell/cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 58, in metaversion
    return self.get_nearest_version(self.link.rev)
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 120, in get_nearest_version
    result = self._call('describe', '--contains', ref)[0]
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 141, in _call
    logger.error(result.stderr)
Message: b"fatal: cannot describe 'ddcda12bd76a0c69bbbadc5d2826394288f3af64'\n"
Arguments: ()
⠙ layers: 1, mutations: 0--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/site-packages/dephell/logging_helpers.py", line 100, in format
    record.msg = Fore.WHITE + record.msg + Fore.RESET
TypeError: can only concatenate str (not "bytes") to str
Call stack:
  File "/usr/bin/dephell", line 11, in <module>
    load_entry_point('dephell==0.8.3', 'console_scripts', 'dephell')()
  File "/usr/lib/python3.8/site-packages/dephell/cli.py", line 84, in entrypoint
    exit(main(argv[1:]))
  File "/usr/lib/python3.8/site-packages/dephell/cli.py", line 66, in main
    result = handler()
  File "/usr/lib/python3.8/site-packages/dephell/commands/deps_convert.py", line 59, in __call__
    resolved = resolver.resolve(silent=self.config['silent'])
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 90, in resolve
    resolved = self._resolve(debug=debug, silent=silent, level=level, spinner=spinner)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 119, in _resolve
    no_conflicts = self._apply_deps(deps, debug=debug)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 208, in _apply_deps
    conflict = self.apply(dep)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 53, in apply
    if not other_dep.compat:
  File "/usr/lib/python3.8/site-packages/dephell/models/dependency.py", line 154, in compat
    for group in self.groups:
  File "/usr/lib/python3.8/site-packages/dephell/models/groups.py", line 173, in __iter__
    if len(self.releases) <= i:
  File "/usr/lib/python3.8/site-packages/dephell/cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/lib/python3.8/site-packages/dephell/models/groups.py", line 37, in releases
    releases = self.dep.repo.get_releases(self.dep)
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 76, in get_releases
    for tag, time in reversed(self.tags.items()):
  File "/usr/lib/python3.8/site-packages/dephell/cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 40, in tags
    self._setup()
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 182, in _setup
    self._call(
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 141, in _call
    logger.error(result.stderr)
Message: b"Cloning into 'django-oscar'...\nerror: RPC failed; curl 18 transfer closed with outstanding read data remaining\nfatal: the remote end hung up unexpectedly\nfatal: early EOF\nfatal: index-pack failed\n"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/site-packages/dephell/logging_helpers.py", line 100, in format
    record.msg = Fore.WHITE + record.msg + Fore.RESET
TypeError: can only concatenate str (not "bytes") to str
Call stack:
  File "/usr/bin/dephell", line 11, in <module>
    load_entry_point('dephell==0.8.3', 'console_scripts', 'dephell')()
  File "/usr/lib/python3.8/site-packages/dephell/cli.py", line 84, in entrypoint
    exit(main(argv[1:]))
  File "/usr/lib/python3.8/site-packages/dephell/cli.py", line 66, in main
    result = handler()
  File "/usr/lib/python3.8/site-packages/dephell/commands/deps_convert.py", line 59, in __call__
    resolved = resolver.resolve(silent=self.config['silent'])
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 90, in resolve
    resolved = self._resolve(debug=debug, silent=silent, level=level, spinner=spinner)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 119, in _resolve
    no_conflicts = self._apply_deps(deps, debug=debug)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 208, in _apply_deps
    conflict = self.apply(dep)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 53, in apply
    if not other_dep.compat:
  File "/usr/lib/python3.8/site-packages/dephell/models/dependency.py", line 154, in compat
    for group in self.groups:
  File "/usr/lib/python3.8/site-packages/dephell/models/groups.py", line 173, in __iter__
    if len(self.releases) <= i:
  File "/usr/lib/python3.8/site-packages/dephell/cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/lib/python3.8/site-packages/dephell/models/groups.py", line 37, in releases
    releases = self.dep.repo.get_releases(self.dep)
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 76, in get_releases
    for tag, time in reversed(self.tags.items()):
  File "/usr/lib/python3.8/site-packages/dephell/cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 40, in tags
    self._setup()
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 188, in _setup
    self._call('checkout', self.link.rev)
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 141, in _call
    logger.error(result.stderr)
Message: b'fatal: not a git repository (or any parent up to mount point /)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/site-packages/dephell/logging_helpers.py", line 100, in format
    record.msg = Fore.WHITE + record.msg + Fore.RESET
TypeError: can only concatenate str (not "bytes") to str
Call stack:
  File "/usr/bin/dephell", line 11, in <module>
    load_entry_point('dephell==0.8.3', 'console_scripts', 'dephell')()
  File "/usr/lib/python3.8/site-packages/dephell/cli.py", line 84, in entrypoint
    exit(main(argv[1:]))
  File "/usr/lib/python3.8/site-packages/dephell/cli.py", line 66, in main
    result = handler()
  File "/usr/lib/python3.8/site-packages/dephell/commands/deps_convert.py", line 59, in __call__
    resolved = resolver.resolve(silent=self.config['silent'])
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 90, in resolve
    resolved = self._resolve(debug=debug, silent=silent, level=level, spinner=spinner)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 119, in _resolve
    no_conflicts = self._apply_deps(deps, debug=debug)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 208, in _apply_deps
    conflict = self.apply(dep)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 53, in apply
    if not other_dep.compat:
  File "/usr/lib/python3.8/site-packages/dephell/models/dependency.py", line 154, in compat
    for group in self.groups:
  File "/usr/lib/python3.8/site-packages/dephell/models/groups.py", line 173, in __iter__
    if len(self.releases) <= i:
  File "/usr/lib/python3.8/site-packages/dephell/cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/lib/python3.8/site-packages/dephell/models/groups.py", line 37, in releases
    releases = self.dep.repo.get_releases(self.dep)
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 76, in get_releases
    for tag, time in reversed(self.tags.items()):
  File "/usr/lib/python3.8/site-packages/dephell/cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 41, in tags
    tags = self._call('tag')
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 141, in _call
    logger.error(result.stderr)
Message: b'fatal: not a git repository (or any parent up to mount point /)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib/python3.8/site-packages/dephell/logging_helpers.py", line 100, in format
    record.msg = Fore.WHITE + record.msg + Fore.RESET
TypeError: can only concatenate str (not "bytes") to str
Call stack:
  File "/usr/bin/dephell", line 11, in <module>
    load_entry_point('dephell==0.8.3', 'console_scripts', 'dephell')()
  File "/usr/lib/python3.8/site-packages/dephell/cli.py", line 84, in entrypoint
    exit(main(argv[1:]))
  File "/usr/lib/python3.8/site-packages/dephell/cli.py", line 66, in main
    result = handler()
  File "/usr/lib/python3.8/site-packages/dephell/commands/deps_convert.py", line 59, in __call__
    resolved = resolver.resolve(silent=self.config['silent'])
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 90, in resolve
    resolved = self._resolve(debug=debug, silent=silent, level=level, spinner=spinner)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 119, in _resolve
    no_conflicts = self._apply_deps(deps, debug=debug)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 208, in _apply_deps
    conflict = self.apply(dep)
  File "/usr/lib/python3.8/site-packages/dephell/controllers/_resolver.py", line 53, in apply
    if not other_dep.compat:
  File "/usr/lib/python3.8/site-packages/dephell/models/dependency.py", line 154, in compat
    for group in self.groups:
  File "/usr/lib/python3.8/site-packages/dephell/models/groups.py", line 173, in __iter__
    if len(self.releases) <= i:
  File "/usr/lib/python3.8/site-packages/dephell/cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/lib/python3.8/site-packages/dephell/models/groups.py", line 37, in releases
    releases = self.dep.repo.get_releases(self.dep)
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 76, in get_releases
    for tag, time in reversed(self.tags.items()):
  File "/usr/lib/python3.8/site-packages/dephell/cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 42, in tags
    result = [(tag, self._get_rev_time(tag)) for tag in tags]
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 42, in <listcomp>
    result = [(tag, self._get_rev_time(tag)) for tag in tags]
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 145, in _get_rev_time
    data = self._call('show', '-s', r'--format="%cI"', rev)
  File "/usr/lib/python3.8/site-packages/dephell/repositories/_git/git.py", line 141, in _call
    logger.error(result.stderr)
Message: b'fatal: not a git repository (or any parent up to mount point /)\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n'
Arguments: ()
ERROR ValueError: time data '' does not match format '%Y-%m-%dT%H:%M:%S%z'
```

**Comment by jayvdb** [comment]
`--level DEBUG` didn't show anything significant
```py
WARNING cannot find tool.dephell section in the config (path=pyproject.toml)
DEBUG load dependencies... (format=poetry, path=pyproject.toml)
DEBUG resolving... 
⠋ layers: 1, mutations: 0--- Logging error ---
...
```

Need more debugging.. ;-)
