### ISSUE TITLE
dephell dep --help throws traceback

### ISSUE THREAD

**Issue by mimi1vx** [dephell/dephell#456]
## Short description

simple call `dephell dep --help` throw traceback

## Output

simple warning about nonexistent command

## Steps to reproduce

```bash
$ dephell dep --help
...
```

## Traceback

```
Traceback (most recent call last):
  File "/usr/bin/dephell", line 11, in <module>
    load_entry_point('dephell==0.8.3', 'console_scripts', 'dephell')()
  File "/usr/lib/python3.8/site-packages/dephell/cli.py", line 84, in entrypoint
    exit(main(argv[1:]))
  File "/usr/lib/python3.8/site-packages/dephell/cli.py", line 44, in main
    parser._print_message(parser.format_help(command=command))
  File "/usr/lib/python3.8/site-packages/dephell_argparse/_parser.py", line 163, in format_help
    self._format_commands(formatter=formatter, command=command)
  File "/usr/lib/python3.8/site-packages/dephell_argparse/_parser.py", line 183, in _format_commands
    elif command.guesses:
  File "/usr/lib/python3.8/site-packages/dephell_argparse/_cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/lib/python3.8/site-packages/dephell_argparse/_command.py", line 85, in guesses
    for name in self.argv[:2]:
  File "/usr/lib/python3.8/site-packages/dephell_argparse/_command.py", line 29, in argv
    return self._argv[self.words:]
  File "/usr/lib/python3.8/site-packages/dephell_argparse/_cached_property.py", line 18, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/lib/python3.8/site-packages/dephell_argparse/_command.py", line 25, in words
    return len(self.match.split())
AttributeError: 'NoneType' object has no attribute 'split'

...
```

## Config

```toml
[tool.dephell.main]
...
```

# Versions

```json
...
```

**Comment by orsinium** [comment]
Please, use issue template and fill in `Versions` section.
