### ISSUE TITLE
ImportError when setup.py tries to import local modules 

### ISSUE THREAD

**Issue by espdev** [dephell/dephell#52]
We are trying to use `dephell deps tree` command  with `--from=setup.py` for projects [ipython](https://github.com/ipython/ipython) or [jupyter_console](https://github.com/jupyter/jupyter_console) and it does not work.

We are getting the following errors:

* for ipython
```
(dephell)$ dephell deps tree --from=/path/to/ipython/setup.py --traceback
WARNING cannot find config file 
ERROR ImportError: No module named 'setupbase' 
ERROR distribution was not called 
ERROR ImportError: No module named 'setupbase' 
Traceback (most recent call last):
  File "/home/espdev/workspace/venvs/dephell/lib/python3.5/site-packages/dephell/cli.py", line 75, in main
    result = task()
  File "/home/espdev/workspace/venvs/dephell/lib/python3.5/site-packages/dephell/commands/deps_tree.py", line 40, in __call__
    resolver = loader.load_resolver(path=self.config['from']['path'])
  File "/home/espdev/workspace/venvs/dephell/lib/python3.5/site-packages/dephell/converters/base.py", line 69, in load_resolver
    root = self.load(path)
  File "/home/espdev/workspace/venvs/dephell/lib/python3.5/site-packages/dephell/converters/setuppy.py", line 83, in load
    info = run_setup(path.name)
  File "/usr/lib/python3.5/distutils/core.py", line 216, in run_setup
    exec(f.read(), g, l)
  File "<string>", line 69, in <module>
ImportError: No module named 'setupbase'
```

* for jupyter_console
```
(dephell)$ dephell deps tree --from=/path/to/jupyter_console/setup.py --traceback
WARNING cannot find config file 
ERROR SyntaxError: invalid syntax (<string>, line 1) 
ERROR distribution was not called 
ERROR RuntimeError: 'distutils.core.setup()' was never called -- perhaps 'setup.py' is not a Distutils setup script? 
Traceback (most recent call last):
  File "/home/espdev/workspace/venvs/dephell/lib/python3.5/site-packages/dephell/cli.py", line 75, in main
    result = task()
  File "/home/espdev/workspace/venvs/dephell/lib/python3.5/site-packages/dephell/commands/deps_tree.py", line 40, in __call__
    resolver = loader.load_resolver(path=self.config['from']['path'])
  File "/home/espdev/workspace/venvs/dephell/lib/python3.5/site-packages/dephell/converters/base.py", line 69, in load_resolver
    root = self.load(path)
  File "/home/espdev/workspace/venvs/dephell/lib/python3.5/site-packages/dephell/converters/setuppy.py", line 83, in load
    info = run_setup(path.name)
  File "/usr/lib/python3.5/distutils/core.py", line 228, in run_setup
    script_name)
RuntimeError: 'distutils.core.setup()' was never called -- perhaps 'setup.py' is not a Distutils setup script?
```

**Comment by orsinium** [comment]
I've renamed the issue to make it more clear. Don't you mind?

**Comment by espdev** [comment]
Of course, I do not mind

And I have checked matplotlib 3.0.0:
```
(dephell)$ dephell deps tree --from=matplotlib/setup.py --traceback
WARNING cannot find config file 
ERROR ImportError: No module named 'setupext' 
ERROR distribution was not called 
ERROR AttributeError: make_release_tree 
Traceback (most recent call last):
  File "/home/espdev/workspace/venvs/dephell/lib/python3.5/site-packages/dephell/cli.py", line 75, in main
    result = task()
  File "/home/espdev/workspace/venvs/dephell/lib/python3.5/site-packages/dephell/commands/deps_tree.py", line 40, in __call__
    resolver = loader.load_resolver(path=self.config['from']['path'])
  File "/home/espdev/workspace/venvs/dephell/lib/python3.5/site-packages/dephell/converters/base.py", line 69, in load_resolver
    root = self.load(path)
  File "/home/espdev/workspace/venvs/dephell/lib/python3.5/site-packages/dephell/converters/setuppy.py", line 83, in load
    info = run_setup(path.name)
  File "/usr/lib/python3.5/distutils/core.py", line 216, in run_setup
    exec(f.read(), g, l)
  File "<string>", line 34, in <module>
AttributeError: make_release_tree
```

Every time a new error occurs :)

**Comment by MrMrRobat** [comment]
I have related issue when trying to determine package version in `setup.py`: 
```python
with open(path.join(PACKAGE_DIR, '__init__.py'), 'r') as init:
    try:
        VERSION = re.findall(r"^__version__ = '([^']+)'\r?$", init.read(), re.M)[0]
    except IndexError:
        raise RuntimeError('Unable to determine version.')
```
Since `dephell` is  capable of finding a package version and keeping `setup.py` up to date, it's not critical, but in some cases may be very frustrating.
