### ISSUE TITLE
No module named dephell_venvs

### ISSUE THREAD

**Issue by b0g3r** [dephell/dephell#55]
` python -m dephell`

```(jibrel-test-assignment-py3.7)  ✘  ~/PycharmProjects/jibrel_test_assignment   master ●✚  python -m dephell
Traceback (most recent call last):
  File "/Users/Boger/.pyenv/versions/3.7.2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/Boger/.pyenv/versions/3.7.2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Boger/Library/Caches/pypoetry/virtualenvs/jibrel-test-assignment-py3.7/lib/python3.7/site-packages/dephell/__main__.py", line 2, in <module>
    from .cli import entrypoint
  File "/Users/Boger/Library/Caches/pypoetry/virtualenvs/jibrel-test-assignment-py3.7/lib/python3.7/site-packages/dephell/cli.py", line 8, in <module>
    from .commands import commands
  File "/Users/Boger/Library/Caches/pypoetry/virtualenvs/jibrel-test-assignment-py3.7/lib/python3.7/site-packages/dephell/commands/__init__.py", line 2, in <module>
    from .autocomplete import AutocompleteCommand
  File "/Users/Boger/Library/Caches/pypoetry/virtualenvs/jibrel-test-assignment-py3.7/lib/python3.7/site-packages/dephell/commands/autocomplete.py", line 10, in <module>
    from ..actions import make_bash_autocomplete, make_zsh_autocomplete
  File "/Users/Boger/Library/Caches/pypoetry/virtualenvs/jibrel-test-assignment-py3.7/lib/python3.7/site-packages/dephell/actions/__init__.py", line 10, in <module>
    from ._entrypoints import get_entrypoints
  File "/Users/Boger/Library/Caches/pypoetry/virtualenvs/jibrel-test-assignment-py3.7/lib/python3.7/site-packages/dephell/actions/_entrypoints.py", line 6, in <module>
    from dephell_venvs import VEnv
ModuleNotFoundError: No module named 'dephell_venvs'
```

**Comment by b0g3r** [comment]
Oh, just unsuccessful CTRL+C while installing packages

**Comment by orsinium** [comment]
:thinking:
